/*
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

Contact: support@infobip.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sms

import (
	"encoding/json"

	. "github.com/infobip/infobip-api-go-client/v3/pkg/infobip"
)

// checks if the UpdateStatusRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateStatusRequest{}

// UpdateStatusRequest struct for UpdateStatusRequest
type UpdateStatusRequest struct {
	Status BulkStatus
}

type _UpdateStatusRequest UpdateStatusRequest

// NewUpdateStatusRequest instantiates a new UpdateStatusRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateStatusRequest(status BulkStatus) *UpdateStatusRequest {
	this := UpdateStatusRequest{}
	this.Status = status
	return &this
}

// NewUpdateStatusRequestWithDefaults instantiates a new UpdateStatusRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateStatusRequestWithDefaults() *UpdateStatusRequest {
	this := UpdateStatusRequest{}
	return &this
}

// GetStatus returns the Status field value
func (o *UpdateStatusRequest) GetStatus() BulkStatus {
	if o == nil {
		var ret BulkStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UpdateStatusRequest) GetStatusOk() (*BulkStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UpdateStatusRequest) SetStatus(v BulkStatus) {
	o.Status = v
}

func (o UpdateStatusRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateStatusRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

type NullableUpdateStatusRequest struct {
	value *UpdateStatusRequest
	isSet bool
}

func (v NullableUpdateStatusRequest) Get() *UpdateStatusRequest {
	return v.value
}

func (v *NullableUpdateStatusRequest) Set(val *UpdateStatusRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateStatusRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateStatusRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateStatusRequest(val *UpdateStatusRequest) *NullableUpdateStatusRequest {
	return &NullableUpdateStatusRequest{value: val, isSet: true}
}

func (v NullableUpdateStatusRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateStatusRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
