/*
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

Contact: support@infobip.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package voice

import (
	"encoding/json"
	"fmt"
)

// AudioContent struct for AudioContent
type AudioContent struct {
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *AudioContent) UnmarshalJSON(data []byte) error {
	return fmt.Errorf("Data failed to match schemas in anyOf(AudioContent)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src AudioContent) MarshalJSON() ([]byte, error) {
	return nil, nil // no data in anyOf schemas
}

// Get the actual instance
func (obj *AudioContent) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	// all schemas are nil
	return nil
}

type NullableAudioContent struct {
	value *AudioContent
	isSet bool
}

func (v NullableAudioContent) Get() *AudioContent {
	return v.value
}

func (v *NullableAudioContent) Set(val *AudioContent) {
	v.value = val
	v.isSet = true
}

func (v NullableAudioContent) IsSet() bool {
	return v.isSet
}

func (v *NullableAudioContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAudioContent(val *AudioContent) *NullableAudioContent {
	return &NullableAudioContent{value: val, isSet: true}
}

func (v NullableAudioContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAudioContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
