/*
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

Contact: support@infobip.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package voice

import (
	"encoding/json"

	. "github.com/infobip/infobip-api-go-client/v3/pkg/infobip"
)

// checks if the CallRoutingFile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CallRoutingFile{}

// CallRoutingFile The list of the results for this page.
type CallRoutingFile struct {
	// File ID.
	Id *string
	// File name.
	Name string
	// File format.
	FileFormat string
	// File size in bytes.
	Size *int64
	// File creation time.
	CreationTime *Time
	// File expiration time.
	ExpirationTime *Time
	// File duration in seconds.
	Duration *int64
}

type _CallRoutingFile CallRoutingFile

// NewCallRoutingFile instantiates a new CallRoutingFile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed

func NewCallRoutingFile(name string, fileFormat string) *CallRoutingFile {
	this := CallRoutingFile{}
	this.Name = name
	this.FileFormat = fileFormat
	return &this
}

// NewCallRoutingFileWithDefaults instantiates a new CallRoutingFile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCallRoutingFileWithDefaults() *CallRoutingFile {
	this := CallRoutingFile{}

	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CallRoutingFile) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CallRoutingFile) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CallRoutingFile) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CallRoutingFile) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value
func (o *CallRoutingFile) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CallRoutingFile) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CallRoutingFile) SetName(v string) {
	o.Name = v
}

// GetFileFormat returns the FileFormat field value
func (o *CallRoutingFile) GetFileFormat() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FileFormat
}

// GetFileFormatOk returns a tuple with the FileFormat field value
// and a boolean to check if the value has been set.
func (o *CallRoutingFile) GetFileFormatOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FileFormat, true
}

// SetFileFormat sets field value
func (o *CallRoutingFile) SetFileFormat(v string) {
	o.FileFormat = v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *CallRoutingFile) GetSize() int64 {
	if o == nil || IsNil(o.Size) {
		var ret int64
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CallRoutingFile) GetSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *CallRoutingFile) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int64 and assigns it to the Size field.
func (o *CallRoutingFile) SetSize(v int64) {
	o.Size = &v
}

// GetCreationTime returns the CreationTime field value if set, zero value otherwise.
func (o *CallRoutingFile) GetCreationTime() Time {
	if o == nil || IsNil(o.CreationTime) {
		var ret Time
		return ret
	}
	return *o.CreationTime
}

// GetCreationTimeOk returns a tuple with the CreationTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CallRoutingFile) GetCreationTimeOk() (*Time, bool) {
	if o == nil || IsNil(o.CreationTime) {
		return nil, false
	}
	return o.CreationTime, true
}

// HasCreationTime returns a boolean if a field has been set.
func (o *CallRoutingFile) HasCreationTime() bool {
	if o != nil && !IsNil(o.CreationTime) {
		return true
	}

	return false
}

// SetCreationTime gets a reference to the given Time and assigns it to the CreationTime field.
func (o *CallRoutingFile) SetCreationTime(v Time) {
	o.CreationTime = &v
}

// GetExpirationTime returns the ExpirationTime field value if set, zero value otherwise.
func (o *CallRoutingFile) GetExpirationTime() Time {
	if o == nil || IsNil(o.ExpirationTime) {
		var ret Time
		return ret
	}
	return *o.ExpirationTime
}

// GetExpirationTimeOk returns a tuple with the ExpirationTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CallRoutingFile) GetExpirationTimeOk() (*Time, bool) {
	if o == nil || IsNil(o.ExpirationTime) {
		return nil, false
	}
	return o.ExpirationTime, true
}

// HasExpirationTime returns a boolean if a field has been set.
func (o *CallRoutingFile) HasExpirationTime() bool {
	if o != nil && !IsNil(o.ExpirationTime) {
		return true
	}

	return false
}

// SetExpirationTime gets a reference to the given Time and assigns it to the ExpirationTime field.
func (o *CallRoutingFile) SetExpirationTime(v Time) {
	o.ExpirationTime = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *CallRoutingFile) GetDuration() int64 {
	if o == nil || IsNil(o.Duration) {
		var ret int64
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CallRoutingFile) GetDurationOk() (*int64, bool) {
	if o == nil || IsNil(o.Duration) {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *CallRoutingFile) HasDuration() bool {
	if o != nil && !IsNil(o.Duration) {
		return true
	}

	return false
}

// SetDuration gets a reference to the given int64 and assigns it to the Duration field.
func (o *CallRoutingFile) SetDuration(v int64) {
	o.Duration = &v
}

func (o CallRoutingFile) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CallRoutingFile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["name"] = o.Name
	toSerialize["fileFormat"] = o.FileFormat
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.CreationTime) {
		toSerialize["creationTime"] = o.CreationTime
	}
	if !IsNil(o.ExpirationTime) {
		toSerialize["expirationTime"] = o.ExpirationTime
	}
	if !IsNil(o.Duration) {
		toSerialize["duration"] = o.Duration
	}
	return toSerialize, nil
}

type NullableCallRoutingFile struct {
	value *CallRoutingFile
	isSet bool
}

func (v NullableCallRoutingFile) Get() *CallRoutingFile {
	return v.value
}

func (v *NullableCallRoutingFile) Set(val *CallRoutingFile) {
	v.value = val
	v.isSet = true
}

func (v NullableCallRoutingFile) IsSet() bool {
	return v.isSet
}

func (v *NullableCallRoutingFile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCallRoutingFile(val *CallRoutingFile) *NullableCallRoutingFile {
	return &NullableCallRoutingFile{value: val, isSet: true}
}

func (v NullableCallRoutingFile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCallRoutingFile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
