/*
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

Contact: support@infobip.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package voice

import (
	"encoding/json"
	"fmt"
)

// CallRoutingRecordingLocation the model 'CallRoutingRecordingLocation'
type CallRoutingRecordingLocation string

// List of CallRoutingRecordingLocation
const (
	CALLROUTINGRECORDINGLOCATION_SAO_PAULO      CallRoutingRecordingLocation = "SAO_PAULO"
	CALLROUTINGRECORDINGLOCATION_BOGOTA         CallRoutingRecordingLocation = "BOGOTA"
	CALLROUTINGRECORDINGLOCATION_FRANKFURT      CallRoutingRecordingLocation = "FRANKFURT"
	CALLROUTINGRECORDINGLOCATION_JOHANNESBURG   CallRoutingRecordingLocation = "JOHANNESBURG"
	CALLROUTINGRECORDINGLOCATION_JOHANNESBURG_1 CallRoutingRecordingLocation = "JOHANNESBURG_1"
	CALLROUTINGRECORDINGLOCATION_NEW_YORK       CallRoutingRecordingLocation = "NEW_YORK"
	CALLROUTINGRECORDINGLOCATION_PORTLAND       CallRoutingRecordingLocation = "PORTLAND"
	CALLROUTINGRECORDINGLOCATION_MOSCOW         CallRoutingRecordingLocation = "MOSCOW"
	CALLROUTINGRECORDINGLOCATION_SINGAPORE      CallRoutingRecordingLocation = "SINGAPORE"
	CALLROUTINGRECORDINGLOCATION_ISTANBUL       CallRoutingRecordingLocation = "ISTANBUL"
	CALLROUTINGRECORDINGLOCATION_KUALA_LUMPUR   CallRoutingRecordingLocation = "KUALA_LUMPUR"
	CALLROUTINGRECORDINGLOCATION_JAKARTA        CallRoutingRecordingLocation = "JAKARTA"
	CALLROUTINGRECORDINGLOCATION_MUMBAI         CallRoutingRecordingLocation = "MUMBAI"
	CALLROUTINGRECORDINGLOCATION_HONG_KONG_1    CallRoutingRecordingLocation = "HONG_KONG_1"
	CALLROUTINGRECORDINGLOCATION_HONG_KONG      CallRoutingRecordingLocation = "HONG_KONG"
	CALLROUTINGRECORDINGLOCATION_RIYADH         CallRoutingRecordingLocation = "RIYADH"
	CALLROUTINGRECORDINGLOCATION_CHENNAI        CallRoutingRecordingLocation = "CHENNAI"
)

// All allowed values of CallRoutingRecordingLocation enum
var AllowedCallRoutingRecordingLocationEnumValues = []CallRoutingRecordingLocation{
	"SAO_PAULO",
	"BOGOTA",
	"FRANKFURT",
	"JOHANNESBURG",
	"JOHANNESBURG_1",
	"NEW_YORK",
	"PORTLAND",
	"MOSCOW",
	"SINGAPORE",
	"ISTANBUL",
	"KUALA_LUMPUR",
	"JAKARTA",
	"MUMBAI",
	"HONG_KONG_1",
	"HONG_KONG",
	"RIYADH",
	"CHENNAI",
}

func (v *CallRoutingRecordingLocation) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CallRoutingRecordingLocation(value)
	for _, existing := range AllowedCallRoutingRecordingLocationEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CallRoutingRecordingLocation", value)
}

// NewCallRoutingRecordingLocationFromValue returns a pointer to a valid CallRoutingRecordingLocation
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCallRoutingRecordingLocationFromValue(v string) (*CallRoutingRecordingLocation, error) {
	ev := CallRoutingRecordingLocation(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CallRoutingRecordingLocation: valid values are %v", v, AllowedCallRoutingRecordingLocationEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CallRoutingRecordingLocation) IsValid() bool {
	for _, existing := range AllowedCallRoutingRecordingLocationEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CallRoutingRecordingLocation value
func (v CallRoutingRecordingLocation) Ptr() *CallRoutingRecordingLocation {
	return &v
}

type NullableCallRoutingRecordingLocation struct {
	value *CallRoutingRecordingLocation
	isSet bool
}

func (v NullableCallRoutingRecordingLocation) Get() *CallRoutingRecordingLocation {
	return v.value
}

func (v *NullableCallRoutingRecordingLocation) Set(val *CallRoutingRecordingLocation) {
	v.value = val
	v.isSet = true
}

func (v NullableCallRoutingRecordingLocation) IsSet() bool {
	return v.isSet
}

func (v *NullableCallRoutingRecordingLocation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCallRoutingRecordingLocation(val *CallRoutingRecordingLocation) *NullableCallRoutingRecordingLocation {
	return &NullableCallRoutingRecordingLocation{value: val, isSet: true}
}

func (v NullableCallRoutingRecordingLocation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCallRoutingRecordingLocation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
