/*
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

Contact: support@infobip.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package voice

import (
	"encoding/json"

	. "github.com/infobip/infobip-api-go-client/v3/pkg/infobip"
)

// checks if the CallRecordingDeletedEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CallRecordingDeletedEvent{}

// CallRecordingDeletedEvent struct for CallRecordingDeletedEvent
type CallRecordingDeletedEvent struct {
	ConferenceId         *string
	CallId               *string
	Timestamp            *Time
	CallsConfigurationId *string
	Platform             *Platform
	BulkId               *string
	DialogId             *string
	Type                 EventType
}

// NewCallRecordingDeletedEvent instantiates a new CallRecordingDeletedEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCallRecordingDeletedEvent() *CallRecordingDeletedEvent {
	this := CallRecordingDeletedEvent{}
	this.Type = "CALL_RECORDING_DELETED"
	return &this
}

// NewCallRecordingDeletedEventWithDefaults instantiates a new CallRecordingDeletedEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCallRecordingDeletedEventWithDefaults() *CallRecordingDeletedEvent {
	this := CallRecordingDeletedEvent{}
	this.Type = "CALL_RECORDING_DELETED"
	return &this
}

// GetConferenceId returns the ConferenceId field value if set, zero value otherwise.
func (o *CallRecordingDeletedEvent) GetConferenceId() string {
	if o == nil || IsNil(o.ConferenceId) {
		var ret string
		return ret
	}
	return *o.ConferenceId
}

// GetConferenceIdOk returns a tuple with the ConferenceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CallRecordingDeletedEvent) GetConferenceIdOk() (*string, bool) {
	if o == nil || IsNil(o.ConferenceId) {
		return nil, false
	}
	return o.ConferenceId, true
}

// HasConferenceId returns a boolean if a field has been set.
func (o *CallRecordingDeletedEvent) HasConferenceId() bool {
	if o != nil && !IsNil(o.ConferenceId) {
		return true
	}

	return false
}

// SetConferenceId gets a reference to the given string and assigns it to the ConferenceId field.
func (o *CallRecordingDeletedEvent) SetConferenceId(v string) {
	o.ConferenceId = &v
}

// GetCallId returns the CallId field value if set, zero value otherwise.
func (o *CallRecordingDeletedEvent) GetCallId() string {
	if o == nil || IsNil(o.CallId) {
		var ret string
		return ret
	}
	return *o.CallId
}

// GetCallIdOk returns a tuple with the CallId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CallRecordingDeletedEvent) GetCallIdOk() (*string, bool) {
	if o == nil || IsNil(o.CallId) {
		return nil, false
	}
	return o.CallId, true
}

// HasCallId returns a boolean if a field has been set.
func (o *CallRecordingDeletedEvent) HasCallId() bool {
	if o != nil && !IsNil(o.CallId) {
		return true
	}

	return false
}

// SetCallId gets a reference to the given string and assigns it to the CallId field.
func (o *CallRecordingDeletedEvent) SetCallId(v string) {
	o.CallId = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *CallRecordingDeletedEvent) GetTimestamp() Time {
	if o == nil || IsNil(o.Timestamp) {
		var ret Time
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CallRecordingDeletedEvent) GetTimestampOk() (*Time, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *CallRecordingDeletedEvent) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given Time and assigns it to the Timestamp field.
func (o *CallRecordingDeletedEvent) SetTimestamp(v Time) {
	o.Timestamp = &v
}

// GetCallsConfigurationId returns the CallsConfigurationId field value if set, zero value otherwise.
func (o *CallRecordingDeletedEvent) GetCallsConfigurationId() string {
	if o == nil || IsNil(o.CallsConfigurationId) {
		var ret string
		return ret
	}
	return *o.CallsConfigurationId
}

// GetCallsConfigurationIdOk returns a tuple with the CallsConfigurationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CallRecordingDeletedEvent) GetCallsConfigurationIdOk() (*string, bool) {
	if o == nil || IsNil(o.CallsConfigurationId) {
		return nil, false
	}
	return o.CallsConfigurationId, true
}

// HasCallsConfigurationId returns a boolean if a field has been set.
func (o *CallRecordingDeletedEvent) HasCallsConfigurationId() bool {
	if o != nil && !IsNil(o.CallsConfigurationId) {
		return true
	}

	return false
}

// SetCallsConfigurationId gets a reference to the given string and assigns it to the CallsConfigurationId field.
func (o *CallRecordingDeletedEvent) SetCallsConfigurationId(v string) {
	o.CallsConfigurationId = &v
}

// GetPlatform returns the Platform field value if set, zero value otherwise.
func (o *CallRecordingDeletedEvent) GetPlatform() Platform {
	if o == nil || IsNil(o.Platform) {
		var ret Platform
		return ret
	}
	return *o.Platform
}

// GetPlatformOk returns a tuple with the Platform field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CallRecordingDeletedEvent) GetPlatformOk() (*Platform, bool) {
	if o == nil || IsNil(o.Platform) {
		return nil, false
	}
	return o.Platform, true
}

// HasPlatform returns a boolean if a field has been set.
func (o *CallRecordingDeletedEvent) HasPlatform() bool {
	if o != nil && !IsNil(o.Platform) {
		return true
	}

	return false
}

// SetPlatform gets a reference to the given Platform and assigns it to the Platform field.
func (o *CallRecordingDeletedEvent) SetPlatform(v Platform) {
	o.Platform = &v
}

// GetBulkId returns the BulkId field value if set, zero value otherwise.
func (o *CallRecordingDeletedEvent) GetBulkId() string {
	if o == nil || IsNil(o.BulkId) {
		var ret string
		return ret
	}
	return *o.BulkId
}

// GetBulkIdOk returns a tuple with the BulkId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CallRecordingDeletedEvent) GetBulkIdOk() (*string, bool) {
	if o == nil || IsNil(o.BulkId) {
		return nil, false
	}
	return o.BulkId, true
}

// HasBulkId returns a boolean if a field has been set.
func (o *CallRecordingDeletedEvent) HasBulkId() bool {
	if o != nil && !IsNil(o.BulkId) {
		return true
	}

	return false
}

// SetBulkId gets a reference to the given string and assigns it to the BulkId field.
func (o *CallRecordingDeletedEvent) SetBulkId(v string) {
	o.BulkId = &v
}

// GetDialogId returns the DialogId field value if set, zero value otherwise.
func (o *CallRecordingDeletedEvent) GetDialogId() string {
	if o == nil || IsNil(o.DialogId) {
		var ret string
		return ret
	}
	return *o.DialogId
}

// GetDialogIdOk returns a tuple with the DialogId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CallRecordingDeletedEvent) GetDialogIdOk() (*string, bool) {
	if o == nil || IsNil(o.DialogId) {
		return nil, false
	}
	return o.DialogId, true
}

// HasDialogId returns a boolean if a field has been set.
func (o *CallRecordingDeletedEvent) HasDialogId() bool {
	if o != nil && !IsNil(o.DialogId) {
		return true
	}

	return false
}

// SetDialogId gets a reference to the given string and assigns it to the DialogId field.
func (o *CallRecordingDeletedEvent) SetDialogId(v string) {
	o.DialogId = &v
}

func (o CallRecordingDeletedEvent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CallRecordingDeletedEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ConferenceId) {
		toSerialize["conferenceId"] = o.ConferenceId
	}
	if !IsNil(o.CallId) {
		toSerialize["callId"] = o.CallId
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	if !IsNil(o.CallsConfigurationId) {
		toSerialize["callsConfigurationId"] = o.CallsConfigurationId
	}
	if !IsNil(o.Platform) {
		toSerialize["platform"] = o.Platform
	}
	if !IsNil(o.BulkId) {
		toSerialize["bulkId"] = o.BulkId
	}
	if !IsNil(o.DialogId) {
		toSerialize["dialogId"] = o.DialogId
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableCallRecordingDeletedEvent struct {
	value *CallRecordingDeletedEvent
	isSet bool
}

func (v NullableCallRecordingDeletedEvent) Get() *CallRecordingDeletedEvent {
	return v.value
}

func (v *NullableCallRecordingDeletedEvent) Set(val *CallRecordingDeletedEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableCallRecordingDeletedEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableCallRecordingDeletedEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCallRecordingDeletedEvent(val *CallRecordingDeletedEvent) *NullableCallRecordingDeletedEvent {
	return &NullableCallRecordingDeletedEvent{value: val, isSet: true}
}

func (v NullableCallRecordingDeletedEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCallRecordingDeletedEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
