/*
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

Contact: support@infobip.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package voice

import (
	"encoding/json"

	. "github.com/infobip/infobip-api-go-client/v3/pkg/infobip"
)

// checks if the CallRoutingRouteResponsePage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CallRoutingRouteResponsePage{}

// CallRoutingRouteResponsePage Routes response object.
type CallRoutingRouteResponsePage struct {
	// The list of the results for this page.
	Results []CallRoutingRouteResponse
	Paging  *PageInfo
}

// NewCallRoutingRouteResponsePage instantiates a new CallRoutingRouteResponsePage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed

func NewCallRoutingRouteResponsePage() *CallRoutingRouteResponsePage {
	this := CallRoutingRouteResponsePage{}
	return &this
}

// NewCallRoutingRouteResponsePageWithDefaults instantiates a new CallRoutingRouteResponsePage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCallRoutingRouteResponsePageWithDefaults() *CallRoutingRouteResponsePage {
	this := CallRoutingRouteResponsePage{}

	return &this
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *CallRoutingRouteResponsePage) GetResults() []CallRoutingRouteResponse {
	if o == nil || IsNil(o.Results) {
		var ret []CallRoutingRouteResponse
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CallRoutingRouteResponsePage) GetResultsOk() ([]CallRoutingRouteResponse, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *CallRoutingRouteResponsePage) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []CallRoutingRouteResponse and assigns it to the Results field.
func (o *CallRoutingRouteResponsePage) SetResults(v []CallRoutingRouteResponse) {
	o.Results = v
}

// GetPaging returns the Paging field value if set, zero value otherwise.
func (o *CallRoutingRouteResponsePage) GetPaging() PageInfo {
	if o == nil || IsNil(o.Paging) {
		var ret PageInfo
		return ret
	}
	return *o.Paging
}

// GetPagingOk returns a tuple with the Paging field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CallRoutingRouteResponsePage) GetPagingOk() (*PageInfo, bool) {
	if o == nil || IsNil(o.Paging) {
		return nil, false
	}
	return o.Paging, true
}

// HasPaging returns a boolean if a field has been set.
func (o *CallRoutingRouteResponsePage) HasPaging() bool {
	if o != nil && !IsNil(o.Paging) {
		return true
	}

	return false
}

// SetPaging gets a reference to the given PageInfo and assigns it to the Paging field.
func (o *CallRoutingRouteResponsePage) SetPaging(v PageInfo) {
	o.Paging = &v
}

func (o CallRoutingRouteResponsePage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CallRoutingRouteResponsePage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	if !IsNil(o.Paging) {
		toSerialize["paging"] = o.Paging
	}
	return toSerialize, nil
}

type NullableCallRoutingRouteResponsePage struct {
	value *CallRoutingRouteResponsePage
	isSet bool
}

func (v NullableCallRoutingRouteResponsePage) Get() *CallRoutingRouteResponsePage {
	return v.value
}

func (v *NullableCallRoutingRouteResponsePage) Set(val *CallRoutingRouteResponsePage) {
	v.value = val
	v.isSet = true
}

func (v NullableCallRoutingRouteResponsePage) IsSet() bool {
	return v.isSet
}

func (v *NullableCallRoutingRouteResponsePage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCallRoutingRouteResponsePage(val *CallRoutingRouteResponsePage) *NullableCallRoutingRouteResponsePage {
	return &NullableCallRoutingRouteResponsePage{value: val, isSet: true}
}

func (v NullableCallRoutingRouteResponsePage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCallRoutingRouteResponsePage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
