/*
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

Contact: support@infobip.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package voice

import (
	"encoding/json"

	. "github.com/infobip/infobip-api-go-client/v3/pkg/infobip"
)

// checks if the DialogWithErrorCodeProperties type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DialogWithErrorCodeProperties{}

// DialogWithErrorCodeProperties Properties of the events that provide `Dialog` object together with `ErrorCode`.
type DialogWithErrorCodeProperties struct {
	Dialog       *Dialog
	ErrorCode    *ErrorCodeInfo
	HangupSource *DialogHangupSource
}

// NewDialogWithErrorCodeProperties instantiates a new DialogWithErrorCodeProperties object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed

func NewDialogWithErrorCodeProperties() *DialogWithErrorCodeProperties {
	this := DialogWithErrorCodeProperties{}
	return &this
}

// NewDialogWithErrorCodePropertiesWithDefaults instantiates a new DialogWithErrorCodeProperties object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDialogWithErrorCodePropertiesWithDefaults() *DialogWithErrorCodeProperties {
	this := DialogWithErrorCodeProperties{}

	return &this
}

// GetDialog returns the Dialog field value if set, zero value otherwise.
func (o *DialogWithErrorCodeProperties) GetDialog() Dialog {
	if o == nil || IsNil(o.Dialog) {
		var ret Dialog
		return ret
	}
	return *o.Dialog
}

// GetDialogOk returns a tuple with the Dialog field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DialogWithErrorCodeProperties) GetDialogOk() (*Dialog, bool) {
	if o == nil || IsNil(o.Dialog) {
		return nil, false
	}
	return o.Dialog, true
}

// HasDialog returns a boolean if a field has been set.
func (o *DialogWithErrorCodeProperties) HasDialog() bool {
	if o != nil && !IsNil(o.Dialog) {
		return true
	}

	return false
}

// SetDialog gets a reference to the given Dialog and assigns it to the Dialog field.
func (o *DialogWithErrorCodeProperties) SetDialog(v Dialog) {
	o.Dialog = &v
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise.
func (o *DialogWithErrorCodeProperties) GetErrorCode() ErrorCodeInfo {
	if o == nil || IsNil(o.ErrorCode) {
		var ret ErrorCodeInfo
		return ret
	}
	return *o.ErrorCode
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DialogWithErrorCodeProperties) GetErrorCodeOk() (*ErrorCodeInfo, bool) {
	if o == nil || IsNil(o.ErrorCode) {
		return nil, false
	}
	return o.ErrorCode, true
}

// HasErrorCode returns a boolean if a field has been set.
func (o *DialogWithErrorCodeProperties) HasErrorCode() bool {
	if o != nil && !IsNil(o.ErrorCode) {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given ErrorCodeInfo and assigns it to the ErrorCode field.
func (o *DialogWithErrorCodeProperties) SetErrorCode(v ErrorCodeInfo) {
	o.ErrorCode = &v
}

// GetHangupSource returns the HangupSource field value if set, zero value otherwise.
func (o *DialogWithErrorCodeProperties) GetHangupSource() DialogHangupSource {
	if o == nil || IsNil(o.HangupSource) {
		var ret DialogHangupSource
		return ret
	}
	return *o.HangupSource
}

// GetHangupSourceOk returns a tuple with the HangupSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DialogWithErrorCodeProperties) GetHangupSourceOk() (*DialogHangupSource, bool) {
	if o == nil || IsNil(o.HangupSource) {
		return nil, false
	}
	return o.HangupSource, true
}

// HasHangupSource returns a boolean if a field has been set.
func (o *DialogWithErrorCodeProperties) HasHangupSource() bool {
	if o != nil && !IsNil(o.HangupSource) {
		return true
	}

	return false
}

// SetHangupSource gets a reference to the given DialogHangupSource and assigns it to the HangupSource field.
func (o *DialogWithErrorCodeProperties) SetHangupSource(v DialogHangupSource) {
	o.HangupSource = &v
}

func (o DialogWithErrorCodeProperties) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DialogWithErrorCodeProperties) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Dialog) {
		toSerialize["dialog"] = o.Dialog
	}
	if !IsNil(o.ErrorCode) {
		toSerialize["errorCode"] = o.ErrorCode
	}
	if !IsNil(o.HangupSource) {
		toSerialize["hangupSource"] = o.HangupSource
	}
	return toSerialize, nil
}

type NullableDialogWithErrorCodeProperties struct {
	value *DialogWithErrorCodeProperties
	isSet bool
}

func (v NullableDialogWithErrorCodeProperties) Get() *DialogWithErrorCodeProperties {
	return v.value
}

func (v *NullableDialogWithErrorCodeProperties) Set(val *DialogWithErrorCodeProperties) {
	v.value = val
	v.isSet = true
}

func (v NullableDialogWithErrorCodeProperties) IsSet() bool {
	return v.isSet
}

func (v *NullableDialogWithErrorCodeProperties) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDialogWithErrorCodeProperties(val *DialogWithErrorCodeProperties) *NullableDialogWithErrorCodeProperties {
	return &NullableDialogWithErrorCodeProperties{value: val, isSet: true}
}

func (v NullableDialogWithErrorCodeProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDialogWithErrorCodeProperties) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
