/*
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

Contact: support@infobip.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package voice

import (
	"encoding/json"

	. "github.com/infobip/infobip-api-go-client/v3/pkg/infobip"
)

// checks if the NumberMaskingUploadResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NumberMaskingUploadResponse{}

// NumberMaskingUploadResponse struct for NumberMaskingUploadResponse
type NumberMaskingUploadResponse struct {
	// Id of the uploaded audio file.
	FileId *string
}

// NewNumberMaskingUploadResponse instantiates a new NumberMaskingUploadResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed

func NewNumberMaskingUploadResponse() *NumberMaskingUploadResponse {
	this := NumberMaskingUploadResponse{}
	return &this
}

// NewNumberMaskingUploadResponseWithDefaults instantiates a new NumberMaskingUploadResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNumberMaskingUploadResponseWithDefaults() *NumberMaskingUploadResponse {
	this := NumberMaskingUploadResponse{}

	return &this
}

// GetFileId returns the FileId field value if set, zero value otherwise.
func (o *NumberMaskingUploadResponse) GetFileId() string {
	if o == nil || IsNil(o.FileId) {
		var ret string
		return ret
	}
	return *o.FileId
}

// GetFileIdOk returns a tuple with the FileId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NumberMaskingUploadResponse) GetFileIdOk() (*string, bool) {
	if o == nil || IsNil(o.FileId) {
		return nil, false
	}
	return o.FileId, true
}

// HasFileId returns a boolean if a field has been set.
func (o *NumberMaskingUploadResponse) HasFileId() bool {
	if o != nil && !IsNil(o.FileId) {
		return true
	}

	return false
}

// SetFileId gets a reference to the given string and assigns it to the FileId field.
func (o *NumberMaskingUploadResponse) SetFileId(v string) {
	o.FileId = &v
}

func (o NumberMaskingUploadResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NumberMaskingUploadResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FileId) {
		toSerialize["fileId"] = o.FileId
	}
	return toSerialize, nil
}

type NullableNumberMaskingUploadResponse struct {
	value *NumberMaskingUploadResponse
	isSet bool
}

func (v NullableNumberMaskingUploadResponse) Get() *NumberMaskingUploadResponse {
	return v.value
}

func (v *NullableNumberMaskingUploadResponse) Set(val *NumberMaskingUploadResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableNumberMaskingUploadResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableNumberMaskingUploadResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNumberMaskingUploadResponse(val *NumberMaskingUploadResponse) *NullableNumberMaskingUploadResponse {
	return &NullableNumberMaskingUploadResponse{value: val, isSet: true}
}

func (v NullableNumberMaskingUploadResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNumberMaskingUploadResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
