/*
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

Contact: support@infobip.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package voice

import (
	"encoding/json"

	. "github.com/infobip/infobip-api-go-client/v3/pkg/infobip"
)

// checks if the NumberMaskingSetupResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NumberMaskingSetupResponse{}

// NumberMaskingSetupResponse struct for NumberMaskingSetupResponse
type NumberMaskingSetupResponse struct {
	// Use to connect masking configuration with Voice-enabled number.
	Key *string
	// Unique configuration name. Alphanumeric, max length 100.
	Name *string
	// Client's URL that will be called on each inbound call to related Number masking Voice number in order to get instructions of how to handle incoming calls. Instructions are a result of mapping logic implemented on your side according to your business case.
	CallbackUrl *string
	// Client's URL for status report delivery after the call is finished.
	StatusUrl *string
	// If callbackUrl is unavailable this one will be called instead.
	BackupCallbackUrl *string
	// If statusUrl is unavailable this one will be called instead.
	BackupStatusUrl *string
	// Masking configuration description
	Description *string
	// Date and time (UTC timezone) when masking configuration is created.
	InsertDateTime *Time
	// Date and time (UTC timezone) when masking configuration was last modified.
	UpdateDateTime *Time
}

// NewNumberMaskingSetupResponse instantiates a new NumberMaskingSetupResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed

func NewNumberMaskingSetupResponse() *NumberMaskingSetupResponse {
	this := NumberMaskingSetupResponse{}
	return &this
}

// NewNumberMaskingSetupResponseWithDefaults instantiates a new NumberMaskingSetupResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNumberMaskingSetupResponseWithDefaults() *NumberMaskingSetupResponse {
	this := NumberMaskingSetupResponse{}

	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *NumberMaskingSetupResponse) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NumberMaskingSetupResponse) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *NumberMaskingSetupResponse) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *NumberMaskingSetupResponse) SetKey(v string) {
	o.Key = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *NumberMaskingSetupResponse) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NumberMaskingSetupResponse) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *NumberMaskingSetupResponse) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *NumberMaskingSetupResponse) SetName(v string) {
	o.Name = &v
}

// GetCallbackUrl returns the CallbackUrl field value if set, zero value otherwise.
func (o *NumberMaskingSetupResponse) GetCallbackUrl() string {
	if o == nil || IsNil(o.CallbackUrl) {
		var ret string
		return ret
	}
	return *o.CallbackUrl
}

// GetCallbackUrlOk returns a tuple with the CallbackUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NumberMaskingSetupResponse) GetCallbackUrlOk() (*string, bool) {
	if o == nil || IsNil(o.CallbackUrl) {
		return nil, false
	}
	return o.CallbackUrl, true
}

// HasCallbackUrl returns a boolean if a field has been set.
func (o *NumberMaskingSetupResponse) HasCallbackUrl() bool {
	if o != nil && !IsNil(o.CallbackUrl) {
		return true
	}

	return false
}

// SetCallbackUrl gets a reference to the given string and assigns it to the CallbackUrl field.
func (o *NumberMaskingSetupResponse) SetCallbackUrl(v string) {
	o.CallbackUrl = &v
}

// GetStatusUrl returns the StatusUrl field value if set, zero value otherwise.
func (o *NumberMaskingSetupResponse) GetStatusUrl() string {
	if o == nil || IsNil(o.StatusUrl) {
		var ret string
		return ret
	}
	return *o.StatusUrl
}

// GetStatusUrlOk returns a tuple with the StatusUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NumberMaskingSetupResponse) GetStatusUrlOk() (*string, bool) {
	if o == nil || IsNil(o.StatusUrl) {
		return nil, false
	}
	return o.StatusUrl, true
}

// HasStatusUrl returns a boolean if a field has been set.
func (o *NumberMaskingSetupResponse) HasStatusUrl() bool {
	if o != nil && !IsNil(o.StatusUrl) {
		return true
	}

	return false
}

// SetStatusUrl gets a reference to the given string and assigns it to the StatusUrl field.
func (o *NumberMaskingSetupResponse) SetStatusUrl(v string) {
	o.StatusUrl = &v
}

// GetBackupCallbackUrl returns the BackupCallbackUrl field value if set, zero value otherwise.
func (o *NumberMaskingSetupResponse) GetBackupCallbackUrl() string {
	if o == nil || IsNil(o.BackupCallbackUrl) {
		var ret string
		return ret
	}
	return *o.BackupCallbackUrl
}

// GetBackupCallbackUrlOk returns a tuple with the BackupCallbackUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NumberMaskingSetupResponse) GetBackupCallbackUrlOk() (*string, bool) {
	if o == nil || IsNil(o.BackupCallbackUrl) {
		return nil, false
	}
	return o.BackupCallbackUrl, true
}

// HasBackupCallbackUrl returns a boolean if a field has been set.
func (o *NumberMaskingSetupResponse) HasBackupCallbackUrl() bool {
	if o != nil && !IsNil(o.BackupCallbackUrl) {
		return true
	}

	return false
}

// SetBackupCallbackUrl gets a reference to the given string and assigns it to the BackupCallbackUrl field.
func (o *NumberMaskingSetupResponse) SetBackupCallbackUrl(v string) {
	o.BackupCallbackUrl = &v
}

// GetBackupStatusUrl returns the BackupStatusUrl field value if set, zero value otherwise.
func (o *NumberMaskingSetupResponse) GetBackupStatusUrl() string {
	if o == nil || IsNil(o.BackupStatusUrl) {
		var ret string
		return ret
	}
	return *o.BackupStatusUrl
}

// GetBackupStatusUrlOk returns a tuple with the BackupStatusUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NumberMaskingSetupResponse) GetBackupStatusUrlOk() (*string, bool) {
	if o == nil || IsNil(o.BackupStatusUrl) {
		return nil, false
	}
	return o.BackupStatusUrl, true
}

// HasBackupStatusUrl returns a boolean if a field has been set.
func (o *NumberMaskingSetupResponse) HasBackupStatusUrl() bool {
	if o != nil && !IsNil(o.BackupStatusUrl) {
		return true
	}

	return false
}

// SetBackupStatusUrl gets a reference to the given string and assigns it to the BackupStatusUrl field.
func (o *NumberMaskingSetupResponse) SetBackupStatusUrl(v string) {
	o.BackupStatusUrl = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *NumberMaskingSetupResponse) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NumberMaskingSetupResponse) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *NumberMaskingSetupResponse) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *NumberMaskingSetupResponse) SetDescription(v string) {
	o.Description = &v
}

// GetInsertDateTime returns the InsertDateTime field value if set, zero value otherwise.
func (o *NumberMaskingSetupResponse) GetInsertDateTime() Time {
	if o == nil || IsNil(o.InsertDateTime) {
		var ret Time
		return ret
	}
	return *o.InsertDateTime
}

// GetInsertDateTimeOk returns a tuple with the InsertDateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NumberMaskingSetupResponse) GetInsertDateTimeOk() (*Time, bool) {
	if o == nil || IsNil(o.InsertDateTime) {
		return nil, false
	}
	return o.InsertDateTime, true
}

// HasInsertDateTime returns a boolean if a field has been set.
func (o *NumberMaskingSetupResponse) HasInsertDateTime() bool {
	if o != nil && !IsNil(o.InsertDateTime) {
		return true
	}

	return false
}

// SetInsertDateTime gets a reference to the given Time and assigns it to the InsertDateTime field.
func (o *NumberMaskingSetupResponse) SetInsertDateTime(v Time) {
	o.InsertDateTime = &v
}

// GetUpdateDateTime returns the UpdateDateTime field value if set, zero value otherwise.
func (o *NumberMaskingSetupResponse) GetUpdateDateTime() Time {
	if o == nil || IsNil(o.UpdateDateTime) {
		var ret Time
		return ret
	}
	return *o.UpdateDateTime
}

// GetUpdateDateTimeOk returns a tuple with the UpdateDateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NumberMaskingSetupResponse) GetUpdateDateTimeOk() (*Time, bool) {
	if o == nil || IsNil(o.UpdateDateTime) {
		return nil, false
	}
	return o.UpdateDateTime, true
}

// HasUpdateDateTime returns a boolean if a field has been set.
func (o *NumberMaskingSetupResponse) HasUpdateDateTime() bool {
	if o != nil && !IsNil(o.UpdateDateTime) {
		return true
	}

	return false
}

// SetUpdateDateTime gets a reference to the given Time and assigns it to the UpdateDateTime field.
func (o *NumberMaskingSetupResponse) SetUpdateDateTime(v Time) {
	o.UpdateDateTime = &v
}

func (o NumberMaskingSetupResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NumberMaskingSetupResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.CallbackUrl) {
		toSerialize["callbackUrl"] = o.CallbackUrl
	}
	if !IsNil(o.StatusUrl) {
		toSerialize["statusUrl"] = o.StatusUrl
	}
	if !IsNil(o.BackupCallbackUrl) {
		toSerialize["backupCallbackUrl"] = o.BackupCallbackUrl
	}
	if !IsNil(o.BackupStatusUrl) {
		toSerialize["backupStatusUrl"] = o.BackupStatusUrl
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.InsertDateTime) {
		toSerialize["insertDateTime"] = o.InsertDateTime
	}
	if !IsNil(o.UpdateDateTime) {
		toSerialize["updateDateTime"] = o.UpdateDateTime
	}
	return toSerialize, nil
}

type NullableNumberMaskingSetupResponse struct {
	value *NumberMaskingSetupResponse
	isSet bool
}

func (v NullableNumberMaskingSetupResponse) Get() *NumberMaskingSetupResponse {
	return v.value
}

func (v *NullableNumberMaskingSetupResponse) Set(val *NumberMaskingSetupResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableNumberMaskingSetupResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableNumberMaskingSetupResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNumberMaskingSetupResponse(val *NumberMaskingSetupResponse) *NullableNumberMaskingSetupResponse {
	return &NullableNumberMaskingSetupResponse{value: val, isSet: true}
}

func (v NullableNumberMaskingSetupResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNumberMaskingSetupResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
