/*
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

Contact: support@infobip.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package voice

import (
	"encoding/json"
	"fmt"
)

// TerminationReason the model 'TerminationReason'
type TerminationReason string

// List of TerminationReason
const (
	TERMINATIONREASON_KEY_PHRASE TerminationReason = "KEY_PHRASE"
	TERMINATIONREASON_SILENCE    TerminationReason = "SILENCE"
	TERMINATIONREASON_TIMEOUT    TerminationReason = "TIMEOUT"
	TERMINATIONREASON_HANGUP     TerminationReason = "HANGUP"
)

// All allowed values of TerminationReason enum
var AllowedTerminationReasonEnumValues = []TerminationReason{
	"KEY_PHRASE",
	"SILENCE",
	"TIMEOUT",
	"HANGUP",
}

func (v *TerminationReason) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := TerminationReason(value)
	for _, existing := range AllowedTerminationReasonEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid TerminationReason", value)
}

// NewTerminationReasonFromValue returns a pointer to a valid TerminationReason
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewTerminationReasonFromValue(v string) (*TerminationReason, error) {
	ev := TerminationReason(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for TerminationReason: valid values are %v", v, AllowedTerminationReasonEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v TerminationReason) IsValid() bool {
	for _, existing := range AllowedTerminationReasonEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to TerminationReason value
func (v TerminationReason) Ptr() *TerminationReason {
	return &v
}

type NullableTerminationReason struct {
	value *TerminationReason
	isSet bool
}

func (v NullableTerminationReason) Get() *TerminationReason {
	return v.value
}

func (v *NullableTerminationReason) Set(val *TerminationReason) {
	v.value = val
	v.isSet = true
}

func (v NullableTerminationReason) IsSet() bool {
	return v.isSet
}

func (v *NullableTerminationReason) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTerminationReason(val *TerminationReason) *NullableTerminationReason {
	return &NullableTerminationReason{value: val, isSet: true}
}

func (v NullableTerminationReason) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTerminationReason) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
