/*
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

Contact: support@infobip.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package voice

import (
	"encoding/json"

	. "github.com/infobip/infobip-api-go-client/v3/pkg/infobip"
)

// checks if the WebsocketEndpointConfigRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebsocketEndpointConfigRequest{}

// WebsocketEndpointConfigRequest struct for WebsocketEndpointConfigRequest
type WebsocketEndpointConfigRequest struct {
	Type RequestMediaStreamConfigType
	Name string
	Url  string
	// Audio sampling rate.
	SampleRate *string
}

type _WebsocketEndpointConfigRequest WebsocketEndpointConfigRequest

// NewWebsocketEndpointConfigRequest instantiates a new WebsocketEndpointConfigRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebsocketEndpointConfigRequest() *WebsocketEndpointConfigRequest {
	this := WebsocketEndpointConfigRequest{}
	this.Type = "WEBSOCKET_ENDPOINT"
	var sampleRate string = "8000"
	this.SampleRate = &sampleRate
	return &this
}

// NewWebsocketEndpointConfigRequestWithDefaults instantiates a new WebsocketEndpointConfigRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebsocketEndpointConfigRequestWithDefaults() *WebsocketEndpointConfigRequest {
	this := WebsocketEndpointConfigRequest{}
	this.Type = "WEBSOCKET_ENDPOINT"
	var sampleRate string = "8000"
	this.SampleRate = &sampleRate
	return &this
}

// GetName returns the Name field value
func (o *WebsocketEndpointConfigRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *WebsocketEndpointConfigRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *WebsocketEndpointConfigRequest) SetName(v string) {
	o.Name = v
}

// GetUrl returns the Url field value
func (o *WebsocketEndpointConfigRequest) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *WebsocketEndpointConfigRequest) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *WebsocketEndpointConfigRequest) SetUrl(v string) {
	o.Url = v
}

// GetSampleRate returns the SampleRate field value if set, zero value otherwise.
func (o *WebsocketEndpointConfigRequest) GetSampleRate() string {
	if o == nil || IsNil(o.SampleRate) {
		var ret string
		return ret
	}
	return *o.SampleRate
}

// GetSampleRateOk returns a tuple with the SampleRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebsocketEndpointConfigRequest) GetSampleRateOk() (*string, bool) {
	if o == nil || IsNil(o.SampleRate) {
		return nil, false
	}
	return o.SampleRate, true
}

// HasSampleRate returns a boolean if a field has been set.
func (o *WebsocketEndpointConfigRequest) HasSampleRate() bool {
	if o != nil && !IsNil(o.SampleRate) {
		return true
	}

	return false
}

// SetSampleRate gets a reference to the given string and assigns it to the SampleRate field.
func (o *WebsocketEndpointConfigRequest) SetSampleRate(v string) {
	o.SampleRate = &v
}

func (o WebsocketEndpointConfigRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebsocketEndpointConfigRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["name"] = o.Name
	toSerialize["url"] = o.Url
	if !IsNil(o.SampleRate) {
		toSerialize["sampleRate"] = o.SampleRate
	}
	return toSerialize, nil
}

type NullableWebsocketEndpointConfigRequest struct {
	value *WebsocketEndpointConfigRequest
	isSet bool
}

func (v NullableWebsocketEndpointConfigRequest) Get() *WebsocketEndpointConfigRequest {
	return v.value
}

func (v *NullableWebsocketEndpointConfigRequest) Set(val *WebsocketEndpointConfigRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWebsocketEndpointConfigRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWebsocketEndpointConfigRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebsocketEndpointConfigRequest(val *WebsocketEndpointConfigRequest) *NullableWebsocketEndpointConfigRequest {
	return &NullableWebsocketEndpointConfigRequest{value: val, isSet: true}
}

func (v NullableWebsocketEndpointConfigRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebsocketEndpointConfigRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
