/*
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

Contact: support@infobip.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package moments

import (
	"encoding/json"

	. "github.com/infobip/infobip-api-go-client/v3/pkg/infobip"
)

// checks if the FormsElementOption type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FormsElementOption{}

// FormsElementOption struct for FormsElementOption
type FormsElementOption struct {
	Name                    string
	Value                   string
	AdditionalConfiguration *map[string]string
}

type _FormsElementOption FormsElementOption

// NewFormsElementOption instantiates a new FormsElementOption object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed

func NewFormsElementOption(name string, value string) *FormsElementOption {
	this := FormsElementOption{}
	this.Name = name
	this.Value = value
	return &this
}

// NewFormsElementOptionWithDefaults instantiates a new FormsElementOption object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFormsElementOptionWithDefaults() *FormsElementOption {
	this := FormsElementOption{}

	return &this
}

// GetName returns the Name field value
func (o *FormsElementOption) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *FormsElementOption) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *FormsElementOption) SetName(v string) {
	o.Name = v
}

// GetValue returns the Value field value
func (o *FormsElementOption) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *FormsElementOption) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *FormsElementOption) SetValue(v string) {
	o.Value = v
}

// GetAdditionalConfiguration returns the AdditionalConfiguration field value if set, zero value otherwise.
func (o *FormsElementOption) GetAdditionalConfiguration() map[string]string {
	if o == nil || IsNil(o.AdditionalConfiguration) {
		var ret map[string]string
		return ret
	}
	return *o.AdditionalConfiguration
}

// GetAdditionalConfigurationOk returns a tuple with the AdditionalConfiguration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FormsElementOption) GetAdditionalConfigurationOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.AdditionalConfiguration) {
		return nil, false
	}
	return o.AdditionalConfiguration, true
}

// HasAdditionalConfiguration returns a boolean if a field has been set.
func (o *FormsElementOption) HasAdditionalConfiguration() bool {
	if o != nil && !IsNil(o.AdditionalConfiguration) {
		return true
	}

	return false
}

// SetAdditionalConfiguration gets a reference to the given map[string]string and assigns it to the AdditionalConfiguration field.
func (o *FormsElementOption) SetAdditionalConfiguration(v map[string]string) {
	o.AdditionalConfiguration = &v
}

func (o FormsElementOption) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FormsElementOption) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["value"] = o.Value
	if !IsNil(o.AdditionalConfiguration) {
		toSerialize["additionalConfiguration"] = o.AdditionalConfiguration
	}
	return toSerialize, nil
}

type NullableFormsElementOption struct {
	value *FormsElementOption
	isSet bool
}

func (v NullableFormsElementOption) Get() *FormsElementOption {
	return v.value
}

func (v *NullableFormsElementOption) Set(val *FormsElementOption) {
	v.value = val
	v.isSet = true
}

func (v NullableFormsElementOption) IsSet() bool {
	return v.isSet
}

func (v *NullableFormsElementOption) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFormsElementOption(val *FormsElementOption) *NullableFormsElementOption {
	return &NullableFormsElementOption{value: val, isSet: true}
}

func (v NullableFormsElementOption) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFormsElementOption) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
