/*
 * Infobip Client API Libraries OpenAPI Specification
 *
 * OpenAPI specification containing public endpoints supported in client API libraries.
 *
 * API version: 1.0.157
 * Contact: support@infobip.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package infobip

import (
	"encoding/json"
)

// SmsApiRequestErrorDetails struct for SmsApiRequestErrorDetails
type SmsApiRequestErrorDetails struct {
	// Identifier of the error.
	MessageId *string `json:"messageId,omitempty"`
	// Detailed error description.
	Text *string `json:"text,omitempty"`
}

// NewSmsApiRequestErrorDetails instantiates a new SmsApiRequestErrorDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSmsApiRequestErrorDetails() *SmsApiRequestErrorDetails {
	this := SmsApiRequestErrorDetails{}
	return &this
}

// NewSmsApiRequestErrorDetailsWithDefaults instantiates a new SmsApiRequestErrorDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSmsApiRequestErrorDetailsWithDefaults() *SmsApiRequestErrorDetails {
	this := SmsApiRequestErrorDetails{}
	return &this
}

// GetMessageId returns the MessageId field value if set, zero value otherwise.
func (o *SmsApiRequestErrorDetails) GetMessageId() string {
	if o == nil || o.MessageId == nil {
		var ret string
		return ret
	}
	return *o.MessageId
}

// GetMessageIdOk returns a tuple with the MessageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmsApiRequestErrorDetails) GetMessageIdOk() (*string, bool) {
	if o == nil || o.MessageId == nil {
		return nil, false
	}
	return o.MessageId, true
}

// HasMessageId returns a boolean if a field has been set.
func (o *SmsApiRequestErrorDetails) HasMessageId() bool {
	if o != nil && o.MessageId != nil {
		return true
	}

	return false
}

// SetMessageId gets a reference to the given string and assigns it to the MessageId field.
func (o *SmsApiRequestErrorDetails) SetMessageId(v string) {
	o.MessageId = &v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *SmsApiRequestErrorDetails) GetText() string {
	if o == nil || o.Text == nil {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmsApiRequestErrorDetails) GetTextOk() (*string, bool) {
	if o == nil || o.Text == nil {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *SmsApiRequestErrorDetails) HasText() bool {
	if o != nil && o.Text != nil {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *SmsApiRequestErrorDetails) SetText(v string) {
	o.Text = &v
}

func (o SmsApiRequestErrorDetails) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.MessageId != nil {
		toSerialize["messageId"] = o.MessageId
	}
	if o.Text != nil {
		toSerialize["text"] = o.Text
	}
	return json.Marshal(toSerialize)
}

type NullableSmsApiRequestErrorDetails struct {
	value *SmsApiRequestErrorDetails
	isSet bool
}

func (v NullableSmsApiRequestErrorDetails) Get() *SmsApiRequestErrorDetails {
	return v.value
}

func (v *NullableSmsApiRequestErrorDetails) Set(val *SmsApiRequestErrorDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableSmsApiRequestErrorDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableSmsApiRequestErrorDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSmsApiRequestErrorDetails(val *SmsApiRequestErrorDetails) *NullableSmsApiRequestErrorDetails {
	return &NullableSmsApiRequestErrorDetails{value: val, isSet: true}
}

func (v NullableSmsApiRequestErrorDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSmsApiRequestErrorDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
