/*
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

Contact: support@infobip.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package messagesapi

import (
	"encoding/json"

	. "github.com/infobip/infobip-api-go-client/v3/pkg/infobip"
)

// checks if the DefaultMessageRequestOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DefaultMessageRequestOptions{}

// DefaultMessageRequestOptions Options applicable to all messages in the request.
type DefaultMessageRequestOptions struct {
	Schedule *RequestSchedulingSettings
	Tracking *UrlOptions
}

// NewDefaultMessageRequestOptions instantiates a new DefaultMessageRequestOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed

func NewDefaultMessageRequestOptions() *DefaultMessageRequestOptions {
	this := DefaultMessageRequestOptions{}
	return &this
}

// NewDefaultMessageRequestOptionsWithDefaults instantiates a new DefaultMessageRequestOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDefaultMessageRequestOptionsWithDefaults() *DefaultMessageRequestOptions {
	this := DefaultMessageRequestOptions{}

	return &this
}

// GetSchedule returns the Schedule field value if set, zero value otherwise.
func (o *DefaultMessageRequestOptions) GetSchedule() RequestSchedulingSettings {
	if o == nil || IsNil(o.Schedule) {
		var ret RequestSchedulingSettings
		return ret
	}
	return *o.Schedule
}

// GetScheduleOk returns a tuple with the Schedule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DefaultMessageRequestOptions) GetScheduleOk() (*RequestSchedulingSettings, bool) {
	if o == nil || IsNil(o.Schedule) {
		return nil, false
	}
	return o.Schedule, true
}

// HasSchedule returns a boolean if a field has been set.
func (o *DefaultMessageRequestOptions) HasSchedule() bool {
	if o != nil && !IsNil(o.Schedule) {
		return true
	}

	return false
}

// SetSchedule gets a reference to the given RequestSchedulingSettings and assigns it to the Schedule field.
func (o *DefaultMessageRequestOptions) SetSchedule(v RequestSchedulingSettings) {
	o.Schedule = &v
}

// GetTracking returns the Tracking field value if set, zero value otherwise.
func (o *DefaultMessageRequestOptions) GetTracking() UrlOptions {
	if o == nil || IsNil(o.Tracking) {
		var ret UrlOptions
		return ret
	}
	return *o.Tracking
}

// GetTrackingOk returns a tuple with the Tracking field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DefaultMessageRequestOptions) GetTrackingOk() (*UrlOptions, bool) {
	if o == nil || IsNil(o.Tracking) {
		return nil, false
	}
	return o.Tracking, true
}

// HasTracking returns a boolean if a field has been set.
func (o *DefaultMessageRequestOptions) HasTracking() bool {
	if o != nil && !IsNil(o.Tracking) {
		return true
	}

	return false
}

// SetTracking gets a reference to the given UrlOptions and assigns it to the Tracking field.
func (o *DefaultMessageRequestOptions) SetTracking(v UrlOptions) {
	o.Tracking = &v
}

func (o DefaultMessageRequestOptions) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DefaultMessageRequestOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schedule) {
		toSerialize["schedule"] = o.Schedule
	}
	if !IsNil(o.Tracking) {
		toSerialize["tracking"] = o.Tracking
	}
	return toSerialize, nil
}

type NullableDefaultMessageRequestOptions struct {
	value *DefaultMessageRequestOptions
	isSet bool
}

func (v NullableDefaultMessageRequestOptions) Get() *DefaultMessageRequestOptions {
	return v.value
}

func (v *NullableDefaultMessageRequestOptions) Set(val *DefaultMessageRequestOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableDefaultMessageRequestOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableDefaultMessageRequestOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDefaultMessageRequestOptions(val *DefaultMessageRequestOptions) *NullableDefaultMessageRequestOptions {
	return &NullableDefaultMessageRequestOptions{value: val, isSet: true}
}

func (v NullableDefaultMessageRequestOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDefaultMessageRequestOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
