/*
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

Contact: support@infobip.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package messagesapi

import (
	"encoding/json"

	. "github.com/infobip/infobip-api-go-client/v3/pkg/infobip"
)

// checks if the MessageFormPickerPageItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MessageFormPickerPageItem{}

// MessageFormPickerPageItem An array of objects defining the user experience.
type MessageFormPickerPageItem struct {
	// Unique identifier of the item.
	Identifier string
	// Title of the item.
	Title string
	// Value of the item.
	Value string
}

type _MessageFormPickerPageItem MessageFormPickerPageItem

// NewMessageFormPickerPageItem instantiates a new MessageFormPickerPageItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed

func NewMessageFormPickerPageItem(identifier string, title string, value string) *MessageFormPickerPageItem {
	this := MessageFormPickerPageItem{}
	this.Identifier = identifier
	this.Title = title
	this.Value = value
	return &this
}

// NewMessageFormPickerPageItemWithDefaults instantiates a new MessageFormPickerPageItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessageFormPickerPageItemWithDefaults() *MessageFormPickerPageItem {
	this := MessageFormPickerPageItem{}

	return &this
}

// GetIdentifier returns the Identifier field value
func (o *MessageFormPickerPageItem) GetIdentifier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value
// and a boolean to check if the value has been set.
func (o *MessageFormPickerPageItem) GetIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Identifier, true
}

// SetIdentifier sets field value
func (o *MessageFormPickerPageItem) SetIdentifier(v string) {
	o.Identifier = v
}

// GetTitle returns the Title field value
func (o *MessageFormPickerPageItem) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *MessageFormPickerPageItem) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *MessageFormPickerPageItem) SetTitle(v string) {
	o.Title = v
}

// GetValue returns the Value field value
func (o *MessageFormPickerPageItem) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *MessageFormPickerPageItem) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *MessageFormPickerPageItem) SetValue(v string) {
	o.Value = v
}

func (o MessageFormPickerPageItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MessageFormPickerPageItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["identifier"] = o.Identifier
	toSerialize["title"] = o.Title
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

type NullableMessageFormPickerPageItem struct {
	value *MessageFormPickerPageItem
	isSet bool
}

func (v NullableMessageFormPickerPageItem) Get() *MessageFormPickerPageItem {
	return v.value
}

func (v *NullableMessageFormPickerPageItem) Set(val *MessageFormPickerPageItem) {
	v.value = val
	v.isSet = true
}

func (v NullableMessageFormPickerPageItem) IsSet() bool {
	return v.isSet
}

func (v *NullableMessageFormPickerPageItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessageFormPickerPageItem(val *MessageFormPickerPageItem) *NullableMessageFormPickerPageItem {
	return &NullableMessageFormPickerPageItem{value: val, isSet: true}
}

func (v NullableMessageFormPickerPageItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessageFormPickerPageItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
