/*
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

Contact: support@infobip.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package messagesapi

import (
	"encoding/json"

	. "github.com/infobip/infobip-api-go-client/v3/pkg/infobip"
)

// checks if the MessageOrderRequestBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MessageOrderRequestBody{}

// MessageOrderRequestBody struct for MessageOrderRequestBody
type MessageOrderRequestBody struct {
	Type MessageBodyType
	// Payment request title.
	Text string
	// (Apple specific) Payment request subtitle
	Subtext *string
	// URL of an image sent.
	ImageUrl *string
	Order    *MessageOrder
	Payment  MessagePayment
	// An array of shipping information. For WhatsApp only one item allowed, for Apple many allowed.
	Shippings []MessageShipping
}

type _MessageOrderRequestBody MessageOrderRequestBody

// NewMessageOrderRequestBody instantiates a new MessageOrderRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMessageOrderRequestBody(text string, payment MessagePayment) *MessageOrderRequestBody {
	this := MessageOrderRequestBody{}
	this.Type = "ORDER_REQUEST"
	this.Text = text
	this.Payment = payment
	return &this
}

// NewMessageOrderRequestBodyWithDefaults instantiates a new MessageOrderRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessageOrderRequestBodyWithDefaults() *MessageOrderRequestBody {
	this := MessageOrderRequestBody{}
	this.Type = "ORDER_REQUEST"
	return &this
}

// GetText returns the Text field value
func (o *MessageOrderRequestBody) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *MessageOrderRequestBody) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *MessageOrderRequestBody) SetText(v string) {
	o.Text = v
}

// GetSubtext returns the Subtext field value if set, zero value otherwise.
func (o *MessageOrderRequestBody) GetSubtext() string {
	if o == nil || IsNil(o.Subtext) {
		var ret string
		return ret
	}
	return *o.Subtext
}

// GetSubtextOk returns a tuple with the Subtext field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageOrderRequestBody) GetSubtextOk() (*string, bool) {
	if o == nil || IsNil(o.Subtext) {
		return nil, false
	}
	return o.Subtext, true
}

// HasSubtext returns a boolean if a field has been set.
func (o *MessageOrderRequestBody) HasSubtext() bool {
	if o != nil && !IsNil(o.Subtext) {
		return true
	}

	return false
}

// SetSubtext gets a reference to the given string and assigns it to the Subtext field.
func (o *MessageOrderRequestBody) SetSubtext(v string) {
	o.Subtext = &v
}

// GetImageUrl returns the ImageUrl field value if set, zero value otherwise.
func (o *MessageOrderRequestBody) GetImageUrl() string {
	if o == nil || IsNil(o.ImageUrl) {
		var ret string
		return ret
	}
	return *o.ImageUrl
}

// GetImageUrlOk returns a tuple with the ImageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageOrderRequestBody) GetImageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ImageUrl) {
		return nil, false
	}
	return o.ImageUrl, true
}

// HasImageUrl returns a boolean if a field has been set.
func (o *MessageOrderRequestBody) HasImageUrl() bool {
	if o != nil && !IsNil(o.ImageUrl) {
		return true
	}

	return false
}

// SetImageUrl gets a reference to the given string and assigns it to the ImageUrl field.
func (o *MessageOrderRequestBody) SetImageUrl(v string) {
	o.ImageUrl = &v
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *MessageOrderRequestBody) GetOrder() MessageOrder {
	if o == nil || IsNil(o.Order) {
		var ret MessageOrder
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageOrderRequestBody) GetOrderOk() (*MessageOrder, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *MessageOrderRequestBody) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given MessageOrder and assigns it to the Order field.
func (o *MessageOrderRequestBody) SetOrder(v MessageOrder) {
	o.Order = &v
}

// GetPayment returns the Payment field value
func (o *MessageOrderRequestBody) GetPayment() MessagePayment {
	if o == nil {
		var ret MessagePayment
		return ret
	}

	return o.Payment
}

// GetPaymentOk returns a tuple with the Payment field value
// and a boolean to check if the value has been set.
func (o *MessageOrderRequestBody) GetPaymentOk() (*MessagePayment, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Payment, true
}

// SetPayment sets field value
func (o *MessageOrderRequestBody) SetPayment(v MessagePayment) {
	o.Payment = v
}

// GetShippings returns the Shippings field value if set, zero value otherwise.
func (o *MessageOrderRequestBody) GetShippings() []MessageShipping {
	if o == nil || IsNil(o.Shippings) {
		var ret []MessageShipping
		return ret
	}
	return o.Shippings
}

// GetShippingsOk returns a tuple with the Shippings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageOrderRequestBody) GetShippingsOk() ([]MessageShipping, bool) {
	if o == nil || IsNil(o.Shippings) {
		return nil, false
	}
	return o.Shippings, true
}

// HasShippings returns a boolean if a field has been set.
func (o *MessageOrderRequestBody) HasShippings() bool {
	if o != nil && !IsNil(o.Shippings) {
		return true
	}

	return false
}

// SetShippings gets a reference to the given []MessageShipping and assigns it to the Shippings field.
func (o *MessageOrderRequestBody) SetShippings(v []MessageShipping) {
	o.Shippings = v
}

func (o MessageOrderRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MessageOrderRequestBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["text"] = o.Text
	if !IsNil(o.Subtext) {
		toSerialize["subtext"] = o.Subtext
	}
	if !IsNil(o.ImageUrl) {
		toSerialize["imageUrl"] = o.ImageUrl
	}
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	toSerialize["payment"] = o.Payment
	if !IsNil(o.Shippings) {
		toSerialize["shippings"] = o.Shippings
	}
	return toSerialize, nil
}

type NullableMessageOrderRequestBody struct {
	value *MessageOrderRequestBody
	isSet bool
}

func (v NullableMessageOrderRequestBody) Get() *MessageOrderRequestBody {
	return v.value
}

func (v *NullableMessageOrderRequestBody) Set(val *MessageOrderRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableMessageOrderRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableMessageOrderRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessageOrderRequestBody(val *MessageOrderRequestBody) *NullableMessageOrderRequestBody {
	return &NullableMessageOrderRequestBody{value: val, isSet: true}
}

func (v NullableMessageOrderRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessageOrderRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
