/*
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

Contact: support@infobip.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package messagesapi

import (
	"encoding/json"

	. "github.com/infobip/infobip-api-go-client/v3/pkg/infobip"
)

// checks if the MessageOrderImporterAddress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MessageOrderImporterAddress{}

// MessageOrderImporterAddress Address of the importer. Required when catalogId is not provided.
type MessageOrderImporterAddress struct {
	// First address line.
	FirstAddressLine *string
	// Second address line.
	SecondAddressLine *string
	// City name.
	City *string
	// Zone code value.
	ZoneCode *string
	// Zip code value.
	PostalCode *string
	// Country code value.
	CountryCode *string
}

// NewMessageOrderImporterAddress instantiates a new MessageOrderImporterAddress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed

func NewMessageOrderImporterAddress() *MessageOrderImporterAddress {
	this := MessageOrderImporterAddress{}
	return &this
}

// NewMessageOrderImporterAddressWithDefaults instantiates a new MessageOrderImporterAddress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessageOrderImporterAddressWithDefaults() *MessageOrderImporterAddress {
	this := MessageOrderImporterAddress{}

	return &this
}

// GetFirstAddressLine returns the FirstAddressLine field value if set, zero value otherwise.
func (o *MessageOrderImporterAddress) GetFirstAddressLine() string {
	if o == nil || IsNil(o.FirstAddressLine) {
		var ret string
		return ret
	}
	return *o.FirstAddressLine
}

// GetFirstAddressLineOk returns a tuple with the FirstAddressLine field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageOrderImporterAddress) GetFirstAddressLineOk() (*string, bool) {
	if o == nil || IsNil(o.FirstAddressLine) {
		return nil, false
	}
	return o.FirstAddressLine, true
}

// HasFirstAddressLine returns a boolean if a field has been set.
func (o *MessageOrderImporterAddress) HasFirstAddressLine() bool {
	if o != nil && !IsNil(o.FirstAddressLine) {
		return true
	}

	return false
}

// SetFirstAddressLine gets a reference to the given string and assigns it to the FirstAddressLine field.
func (o *MessageOrderImporterAddress) SetFirstAddressLine(v string) {
	o.FirstAddressLine = &v
}

// GetSecondAddressLine returns the SecondAddressLine field value if set, zero value otherwise.
func (o *MessageOrderImporterAddress) GetSecondAddressLine() string {
	if o == nil || IsNil(o.SecondAddressLine) {
		var ret string
		return ret
	}
	return *o.SecondAddressLine
}

// GetSecondAddressLineOk returns a tuple with the SecondAddressLine field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageOrderImporterAddress) GetSecondAddressLineOk() (*string, bool) {
	if o == nil || IsNil(o.SecondAddressLine) {
		return nil, false
	}
	return o.SecondAddressLine, true
}

// HasSecondAddressLine returns a boolean if a field has been set.
func (o *MessageOrderImporterAddress) HasSecondAddressLine() bool {
	if o != nil && !IsNil(o.SecondAddressLine) {
		return true
	}

	return false
}

// SetSecondAddressLine gets a reference to the given string and assigns it to the SecondAddressLine field.
func (o *MessageOrderImporterAddress) SetSecondAddressLine(v string) {
	o.SecondAddressLine = &v
}

// GetCity returns the City field value if set, zero value otherwise.
func (o *MessageOrderImporterAddress) GetCity() string {
	if o == nil || IsNil(o.City) {
		var ret string
		return ret
	}
	return *o.City
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageOrderImporterAddress) GetCityOk() (*string, bool) {
	if o == nil || IsNil(o.City) {
		return nil, false
	}
	return o.City, true
}

// HasCity returns a boolean if a field has been set.
func (o *MessageOrderImporterAddress) HasCity() bool {
	if o != nil && !IsNil(o.City) {
		return true
	}

	return false
}

// SetCity gets a reference to the given string and assigns it to the City field.
func (o *MessageOrderImporterAddress) SetCity(v string) {
	o.City = &v
}

// GetZoneCode returns the ZoneCode field value if set, zero value otherwise.
func (o *MessageOrderImporterAddress) GetZoneCode() string {
	if o == nil || IsNil(o.ZoneCode) {
		var ret string
		return ret
	}
	return *o.ZoneCode
}

// GetZoneCodeOk returns a tuple with the ZoneCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageOrderImporterAddress) GetZoneCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ZoneCode) {
		return nil, false
	}
	return o.ZoneCode, true
}

// HasZoneCode returns a boolean if a field has been set.
func (o *MessageOrderImporterAddress) HasZoneCode() bool {
	if o != nil && !IsNil(o.ZoneCode) {
		return true
	}

	return false
}

// SetZoneCode gets a reference to the given string and assigns it to the ZoneCode field.
func (o *MessageOrderImporterAddress) SetZoneCode(v string) {
	o.ZoneCode = &v
}

// GetPostalCode returns the PostalCode field value if set, zero value otherwise.
func (o *MessageOrderImporterAddress) GetPostalCode() string {
	if o == nil || IsNil(o.PostalCode) {
		var ret string
		return ret
	}
	return *o.PostalCode
}

// GetPostalCodeOk returns a tuple with the PostalCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageOrderImporterAddress) GetPostalCodeOk() (*string, bool) {
	if o == nil || IsNil(o.PostalCode) {
		return nil, false
	}
	return o.PostalCode, true
}

// HasPostalCode returns a boolean if a field has been set.
func (o *MessageOrderImporterAddress) HasPostalCode() bool {
	if o != nil && !IsNil(o.PostalCode) {
		return true
	}

	return false
}

// SetPostalCode gets a reference to the given string and assigns it to the PostalCode field.
func (o *MessageOrderImporterAddress) SetPostalCode(v string) {
	o.PostalCode = &v
}

// GetCountryCode returns the CountryCode field value if set, zero value otherwise.
func (o *MessageOrderImporterAddress) GetCountryCode() string {
	if o == nil || IsNil(o.CountryCode) {
		var ret string
		return ret
	}
	return *o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageOrderImporterAddress) GetCountryCodeOk() (*string, bool) {
	if o == nil || IsNil(o.CountryCode) {
		return nil, false
	}
	return o.CountryCode, true
}

// HasCountryCode returns a boolean if a field has been set.
func (o *MessageOrderImporterAddress) HasCountryCode() bool {
	if o != nil && !IsNil(o.CountryCode) {
		return true
	}

	return false
}

// SetCountryCode gets a reference to the given string and assigns it to the CountryCode field.
func (o *MessageOrderImporterAddress) SetCountryCode(v string) {
	o.CountryCode = &v
}

func (o MessageOrderImporterAddress) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MessageOrderImporterAddress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FirstAddressLine) {
		toSerialize["firstAddressLine"] = o.FirstAddressLine
	}
	if !IsNil(o.SecondAddressLine) {
		toSerialize["secondAddressLine"] = o.SecondAddressLine
	}
	if !IsNil(o.City) {
		toSerialize["city"] = o.City
	}
	if !IsNil(o.ZoneCode) {
		toSerialize["zoneCode"] = o.ZoneCode
	}
	if !IsNil(o.PostalCode) {
		toSerialize["postalCode"] = o.PostalCode
	}
	if !IsNil(o.CountryCode) {
		toSerialize["countryCode"] = o.CountryCode
	}
	return toSerialize, nil
}

type NullableMessageOrderImporterAddress struct {
	value *MessageOrderImporterAddress
	isSet bool
}

func (v NullableMessageOrderImporterAddress) Get() *MessageOrderImporterAddress {
	return v.value
}

func (v *NullableMessageOrderImporterAddress) Set(val *MessageOrderImporterAddress) {
	v.value = val
	v.isSet = true
}

func (v NullableMessageOrderImporterAddress) IsSet() bool {
	return v.isSet
}

func (v *NullableMessageOrderImporterAddress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessageOrderImporterAddress(val *MessageOrderImporterAddress) *NullableMessageOrderImporterAddress {
	return &NullableMessageOrderImporterAddress{value: val, isSet: true}
}

func (v NullableMessageOrderImporterAddress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessageOrderImporterAddress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
