/*
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

Contact: support@infobip.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package messagesapi

import (
	"encoding/json"

	. "github.com/infobip/infobip-api-go-client/v3/pkg/infobip"
)

// checks if the MessageUpiPgRazorpayPaymentConfiguration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MessageUpiPgRazorpayPaymentConfiguration{}

// MessageUpiPgRazorpayPaymentConfiguration struct for MessageUpiPgRazorpayPaymentConfiguration
type MessageUpiPgRazorpayPaymentConfiguration struct {
	Type MessagePaymentConfigurationType
	// Unique identifier of the payment. It can only contain English letters, numbers, underscores, dashes, or dots, and should not exceed 35 characters
	Id *string
	// Name of the WhatsApp payment configuration to be used for this order.
	Name        *string
	Beneficiary *MessagePaymentBeneficiary
	// Object with key value pairs containing custom parameters corresponding to the transaction.
	CallbackData *map[string]string
}

type _MessageUpiPgRazorpayPaymentConfiguration MessageUpiPgRazorpayPaymentConfiguration

// NewMessageUpiPgRazorpayPaymentConfiguration instantiates a new MessageUpiPgRazorpayPaymentConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMessageUpiPgRazorpayPaymentConfiguration() *MessageUpiPgRazorpayPaymentConfiguration {
	this := MessageUpiPgRazorpayPaymentConfiguration{}
	this.Type = "PG_RAZORPAY"
	return &this
}

// NewMessageUpiPgRazorpayPaymentConfigurationWithDefaults instantiates a new MessageUpiPgRazorpayPaymentConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessageUpiPgRazorpayPaymentConfigurationWithDefaults() *MessageUpiPgRazorpayPaymentConfiguration {
	this := MessageUpiPgRazorpayPaymentConfiguration{}
	this.Type = "PG_RAZORPAY"
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *MessageUpiPgRazorpayPaymentConfiguration) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageUpiPgRazorpayPaymentConfiguration) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *MessageUpiPgRazorpayPaymentConfiguration) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *MessageUpiPgRazorpayPaymentConfiguration) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *MessageUpiPgRazorpayPaymentConfiguration) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageUpiPgRazorpayPaymentConfiguration) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *MessageUpiPgRazorpayPaymentConfiguration) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *MessageUpiPgRazorpayPaymentConfiguration) SetName(v string) {
	o.Name = &v
}

// GetBeneficiary returns the Beneficiary field value if set, zero value otherwise.
func (o *MessageUpiPgRazorpayPaymentConfiguration) GetBeneficiary() MessagePaymentBeneficiary {
	if o == nil || IsNil(o.Beneficiary) {
		var ret MessagePaymentBeneficiary
		return ret
	}
	return *o.Beneficiary
}

// GetBeneficiaryOk returns a tuple with the Beneficiary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageUpiPgRazorpayPaymentConfiguration) GetBeneficiaryOk() (*MessagePaymentBeneficiary, bool) {
	if o == nil || IsNil(o.Beneficiary) {
		return nil, false
	}
	return o.Beneficiary, true
}

// HasBeneficiary returns a boolean if a field has been set.
func (o *MessageUpiPgRazorpayPaymentConfiguration) HasBeneficiary() bool {
	if o != nil && !IsNil(o.Beneficiary) {
		return true
	}

	return false
}

// SetBeneficiary gets a reference to the given MessagePaymentBeneficiary and assigns it to the Beneficiary field.
func (o *MessageUpiPgRazorpayPaymentConfiguration) SetBeneficiary(v MessagePaymentBeneficiary) {
	o.Beneficiary = &v
}

// GetCallbackData returns the CallbackData field value if set, zero value otherwise.
func (o *MessageUpiPgRazorpayPaymentConfiguration) GetCallbackData() map[string]string {
	if o == nil || IsNil(o.CallbackData) {
		var ret map[string]string
		return ret
	}
	return *o.CallbackData
}

// GetCallbackDataOk returns a tuple with the CallbackData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageUpiPgRazorpayPaymentConfiguration) GetCallbackDataOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.CallbackData) {
		return nil, false
	}
	return o.CallbackData, true
}

// HasCallbackData returns a boolean if a field has been set.
func (o *MessageUpiPgRazorpayPaymentConfiguration) HasCallbackData() bool {
	if o != nil && !IsNil(o.CallbackData) {
		return true
	}

	return false
}

// SetCallbackData gets a reference to the given map[string]string and assigns it to the CallbackData field.
func (o *MessageUpiPgRazorpayPaymentConfiguration) SetCallbackData(v map[string]string) {
	o.CallbackData = &v
}

func (o MessageUpiPgRazorpayPaymentConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MessageUpiPgRazorpayPaymentConfiguration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Beneficiary) {
		toSerialize["beneficiary"] = o.Beneficiary
	}
	if !IsNil(o.CallbackData) {
		toSerialize["callbackData"] = o.CallbackData
	}
	return toSerialize, nil
}

type NullableMessageUpiPgRazorpayPaymentConfiguration struct {
	value *MessageUpiPgRazorpayPaymentConfiguration
	isSet bool
}

func (v NullableMessageUpiPgRazorpayPaymentConfiguration) Get() *MessageUpiPgRazorpayPaymentConfiguration {
	return v.value
}

func (v *NullableMessageUpiPgRazorpayPaymentConfiguration) Set(val *MessageUpiPgRazorpayPaymentConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableMessageUpiPgRazorpayPaymentConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableMessageUpiPgRazorpayPaymentConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessageUpiPgRazorpayPaymentConfiguration(val *MessageUpiPgRazorpayPaymentConfiguration) *NullableMessageUpiPgRazorpayPaymentConfiguration {
	return &NullableMessageUpiPgRazorpayPaymentConfiguration{value: val, isSet: true}
}

func (v NullableMessageUpiPgRazorpayPaymentConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessageUpiPgRazorpayPaymentConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
