/*
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

Contact: support@infobip.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package messagesapi

import (
	"encoding/json"

	. "github.com/infobip/infobip-api-go-client/v3/pkg/infobip"
)

// checks if the MessageCardOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MessageCardOptions{}

// MessageCardOptions Set of alignment options for the Card.
type MessageCardOptions struct {
	Orientation *MessageCardOptionsOrientationEnum
	Alignment   *MessageCardOptionsAlignmentEnum
	Height      *MessageCardOptionsHeightEnum
}

// NewMessageCardOptions instantiates a new MessageCardOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed

func NewMessageCardOptions() *MessageCardOptions {
	this := MessageCardOptions{}
	var orientation MessageCardOptionsOrientationEnum = MESSAGECARDOPTIONSORIENTATIONENUM_VERTICAL
	this.Orientation = &orientation
	var alignment MessageCardOptionsAlignmentEnum = MESSAGECARDOPTIONSALIGNMENTENUM_LEFT
	this.Alignment = &alignment
	var height MessageCardOptionsHeightEnum = MESSAGECARDOPTIONSHEIGHTENUM_MEDIUM
	this.Height = &height
	return &this
}

// NewMessageCardOptionsWithDefaults instantiates a new MessageCardOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessageCardOptionsWithDefaults() *MessageCardOptions {
	this := MessageCardOptions{}

	var orientation MessageCardOptionsOrientationEnum = MESSAGECARDOPTIONSORIENTATIONENUM_VERTICAL
	this.Orientation = &orientation
	var alignment MessageCardOptionsAlignmentEnum = MESSAGECARDOPTIONSALIGNMENTENUM_LEFT
	this.Alignment = &alignment
	var height MessageCardOptionsHeightEnum = MESSAGECARDOPTIONSHEIGHTENUM_MEDIUM
	this.Height = &height
	return &this
}

// GetOrientation returns the Orientation field value if set, zero value otherwise.
func (o *MessageCardOptions) GetOrientation() MessageCardOptionsOrientationEnum {
	if o == nil || IsNil(o.Orientation) {
		var ret MessageCardOptionsOrientationEnum
		return ret
	}
	return *o.Orientation
}

// GetOrientationOk returns a tuple with the Orientation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageCardOptions) GetOrientationOk() (*MessageCardOptionsOrientationEnum, bool) {
	if o == nil || IsNil(o.Orientation) {
		return nil, false
	}
	return o.Orientation, true
}

// HasOrientation returns a boolean if a field has been set.
func (o *MessageCardOptions) HasOrientation() bool {
	if o != nil && !IsNil(o.Orientation) {
		return true
	}

	return false
}

// SetOrientation gets a reference to the given MessageCardOptionsOrientationEnum and assigns it to the Orientation field.
func (o *MessageCardOptions) SetOrientation(v MessageCardOptionsOrientationEnum) {
	o.Orientation = &v
}

// GetAlignment returns the Alignment field value if set, zero value otherwise.
func (o *MessageCardOptions) GetAlignment() MessageCardOptionsAlignmentEnum {
	if o == nil || IsNil(o.Alignment) {
		var ret MessageCardOptionsAlignmentEnum
		return ret
	}
	return *o.Alignment
}

// GetAlignmentOk returns a tuple with the Alignment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageCardOptions) GetAlignmentOk() (*MessageCardOptionsAlignmentEnum, bool) {
	if o == nil || IsNil(o.Alignment) {
		return nil, false
	}
	return o.Alignment, true
}

// HasAlignment returns a boolean if a field has been set.
func (o *MessageCardOptions) HasAlignment() bool {
	if o != nil && !IsNil(o.Alignment) {
		return true
	}

	return false
}

// SetAlignment gets a reference to the given MessageCardOptionsAlignmentEnum and assigns it to the Alignment field.
func (o *MessageCardOptions) SetAlignment(v MessageCardOptionsAlignmentEnum) {
	o.Alignment = &v
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *MessageCardOptions) GetHeight() MessageCardOptionsHeightEnum {
	if o == nil || IsNil(o.Height) {
		var ret MessageCardOptionsHeightEnum
		return ret
	}
	return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageCardOptions) GetHeightOk() (*MessageCardOptionsHeightEnum, bool) {
	if o == nil || IsNil(o.Height) {
		return nil, false
	}
	return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *MessageCardOptions) HasHeight() bool {
	if o != nil && !IsNil(o.Height) {
		return true
	}

	return false
}

// SetHeight gets a reference to the given MessageCardOptionsHeightEnum and assigns it to the Height field.
func (o *MessageCardOptions) SetHeight(v MessageCardOptionsHeightEnum) {
	o.Height = &v
}

func (o MessageCardOptions) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MessageCardOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Orientation) {
		toSerialize["orientation"] = o.Orientation
	}
	if !IsNil(o.Alignment) {
		toSerialize["alignment"] = o.Alignment
	}
	if !IsNil(o.Height) {
		toSerialize["height"] = o.Height
	}
	return toSerialize, nil
}

type NullableMessageCardOptions struct {
	value *MessageCardOptions
	isSet bool
}

func (v NullableMessageCardOptions) Get() *MessageCardOptions {
	return v.value
}

func (v *NullableMessageCardOptions) Set(val *MessageCardOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableMessageCardOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableMessageCardOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessageCardOptions(val *MessageCardOptions) *NullableMessageCardOptions {
	return &NullableMessageCardOptions{value: val, isSet: true}
}

func (v NullableMessageCardOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessageCardOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
