/*
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

Contact: support@infobip.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package messagesapi

import (
	"encoding/json"

	. "github.com/infobip/infobip-api-go-client/v3/pkg/infobip"
)

// checks if the MoEventPaymentResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MoEventPaymentResponseContent{}

// MoEventPaymentResponseContent struct for MoEventPaymentResponseContent
type MoEventPaymentResponseContent struct {
	Type MoEventContentType
	// (WhatsApp specific) Unique identifier generated by the payment service provider.
	ReferenceId *string
	// (WhatsApp specific) Unique identifier of the payment.
	PaymentId *string
	// Status of the payment.
	Status      string
	Total       MoEventPaymentTotal
	Transaction *MoEventPaymentTransaction
	// Items information included in the incoming message.
	Items []MoEventPaymentItem
}

type _MoEventPaymentResponseContent MoEventPaymentResponseContent

// NewMoEventPaymentResponseContent instantiates a new MoEventPaymentResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMoEventPaymentResponseContent(status string, total MoEventPaymentTotal) *MoEventPaymentResponseContent {
	this := MoEventPaymentResponseContent{}
	this.Type = "PAYMENT_RESPONSE"
	this.Status = status
	this.Total = total
	return &this
}

// NewMoEventPaymentResponseContentWithDefaults instantiates a new MoEventPaymentResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMoEventPaymentResponseContentWithDefaults() *MoEventPaymentResponseContent {
	this := MoEventPaymentResponseContent{}
	this.Type = "PAYMENT_RESPONSE"
	return &this
}

// GetReferenceId returns the ReferenceId field value if set, zero value otherwise.
func (o *MoEventPaymentResponseContent) GetReferenceId() string {
	if o == nil || IsNil(o.ReferenceId) {
		var ret string
		return ret
	}
	return *o.ReferenceId
}

// GetReferenceIdOk returns a tuple with the ReferenceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoEventPaymentResponseContent) GetReferenceIdOk() (*string, bool) {
	if o == nil || IsNil(o.ReferenceId) {
		return nil, false
	}
	return o.ReferenceId, true
}

// HasReferenceId returns a boolean if a field has been set.
func (o *MoEventPaymentResponseContent) HasReferenceId() bool {
	if o != nil && !IsNil(o.ReferenceId) {
		return true
	}

	return false
}

// SetReferenceId gets a reference to the given string and assigns it to the ReferenceId field.
func (o *MoEventPaymentResponseContent) SetReferenceId(v string) {
	o.ReferenceId = &v
}

// GetPaymentId returns the PaymentId field value if set, zero value otherwise.
func (o *MoEventPaymentResponseContent) GetPaymentId() string {
	if o == nil || IsNil(o.PaymentId) {
		var ret string
		return ret
	}
	return *o.PaymentId
}

// GetPaymentIdOk returns a tuple with the PaymentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoEventPaymentResponseContent) GetPaymentIdOk() (*string, bool) {
	if o == nil || IsNil(o.PaymentId) {
		return nil, false
	}
	return o.PaymentId, true
}

// HasPaymentId returns a boolean if a field has been set.
func (o *MoEventPaymentResponseContent) HasPaymentId() bool {
	if o != nil && !IsNil(o.PaymentId) {
		return true
	}

	return false
}

// SetPaymentId gets a reference to the given string and assigns it to the PaymentId field.
func (o *MoEventPaymentResponseContent) SetPaymentId(v string) {
	o.PaymentId = &v
}

// GetStatus returns the Status field value
func (o *MoEventPaymentResponseContent) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *MoEventPaymentResponseContent) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *MoEventPaymentResponseContent) SetStatus(v string) {
	o.Status = v
}

// GetTotal returns the Total field value
func (o *MoEventPaymentResponseContent) GetTotal() MoEventPaymentTotal {
	if o == nil {
		var ret MoEventPaymentTotal
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *MoEventPaymentResponseContent) GetTotalOk() (*MoEventPaymentTotal, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *MoEventPaymentResponseContent) SetTotal(v MoEventPaymentTotal) {
	o.Total = v
}

// GetTransaction returns the Transaction field value if set, zero value otherwise.
func (o *MoEventPaymentResponseContent) GetTransaction() MoEventPaymentTransaction {
	if o == nil || IsNil(o.Transaction) {
		var ret MoEventPaymentTransaction
		return ret
	}
	return *o.Transaction
}

// GetTransactionOk returns a tuple with the Transaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoEventPaymentResponseContent) GetTransactionOk() (*MoEventPaymentTransaction, bool) {
	if o == nil || IsNil(o.Transaction) {
		return nil, false
	}
	return o.Transaction, true
}

// HasTransaction returns a boolean if a field has been set.
func (o *MoEventPaymentResponseContent) HasTransaction() bool {
	if o != nil && !IsNil(o.Transaction) {
		return true
	}

	return false
}

// SetTransaction gets a reference to the given MoEventPaymentTransaction and assigns it to the Transaction field.
func (o *MoEventPaymentResponseContent) SetTransaction(v MoEventPaymentTransaction) {
	o.Transaction = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *MoEventPaymentResponseContent) GetItems() []MoEventPaymentItem {
	if o == nil || IsNil(o.Items) {
		var ret []MoEventPaymentItem
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoEventPaymentResponseContent) GetItemsOk() ([]MoEventPaymentItem, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *MoEventPaymentResponseContent) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []MoEventPaymentItem and assigns it to the Items field.
func (o *MoEventPaymentResponseContent) SetItems(v []MoEventPaymentItem) {
	o.Items = v
}

func (o MoEventPaymentResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MoEventPaymentResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.ReferenceId) {
		toSerialize["referenceId"] = o.ReferenceId
	}
	if !IsNil(o.PaymentId) {
		toSerialize["paymentId"] = o.PaymentId
	}
	toSerialize["status"] = o.Status
	toSerialize["total"] = o.Total
	if !IsNil(o.Transaction) {
		toSerialize["transaction"] = o.Transaction
	}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableMoEventPaymentResponseContent struct {
	value *MoEventPaymentResponseContent
	isSet bool
}

func (v NullableMoEventPaymentResponseContent) Get() *MoEventPaymentResponseContent {
	return v.value
}

func (v *NullableMoEventPaymentResponseContent) Set(val *MoEventPaymentResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableMoEventPaymentResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableMoEventPaymentResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMoEventPaymentResponseContent(val *MoEventPaymentResponseContent) *NullableMoEventPaymentResponseContent {
	return &NullableMoEventPaymentResponseContent{value: val, isSet: true}
}

func (v NullableMoEventPaymentResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMoEventPaymentResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
