/*
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

Contact: support@infobip.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package messagesapi

import (
	"encoding/json"

	. "github.com/infobip/infobip-api-go-client/v3/pkg/infobip"
)

// checks if the MoEventFileContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MoEventFileContent{}

// MoEventFileContent struct for MoEventFileContent
type MoEventFileContent struct {
	Type MoEventContentType
	// URL of the file.
	Url string
	// File caption.
	Text *string
}

type _MoEventFileContent MoEventFileContent

// NewMoEventFileContent instantiates a new MoEventFileContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMoEventFileContent(url string) *MoEventFileContent {
	this := MoEventFileContent{}
	this.Type = "FILE"
	this.Url = url
	return &this
}

// NewMoEventFileContentWithDefaults instantiates a new MoEventFileContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMoEventFileContentWithDefaults() *MoEventFileContent {
	this := MoEventFileContent{}
	this.Type = "FILE"
	return &this
}

// GetUrl returns the Url field value
func (o *MoEventFileContent) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *MoEventFileContent) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *MoEventFileContent) SetUrl(v string) {
	o.Url = v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *MoEventFileContent) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoEventFileContent) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *MoEventFileContent) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *MoEventFileContent) SetText(v string) {
	o.Text = &v
}

func (o MoEventFileContent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MoEventFileContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["url"] = o.Url
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	return toSerialize, nil
}

type NullableMoEventFileContent struct {
	value *MoEventFileContent
	isSet bool
}

func (v NullableMoEventFileContent) Get() *MoEventFileContent {
	return v.value
}

func (v *NullableMoEventFileContent) Set(val *MoEventFileContent) {
	v.value = val
	v.isSet = true
}

func (v NullableMoEventFileContent) IsSet() bool {
	return v.isSet
}

func (v *NullableMoEventFileContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMoEventFileContent(val *MoEventFileContent) *NullableMoEventFileContent {
	return &NullableMoEventFileContent{value: val, isSet: true}
}

func (v NullableMoEventFileContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMoEventFileContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
