/*
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

Contact: support@infobip.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package messagesapi

import (
	"encoding/json"

	. "github.com/infobip/infobip-api-go-client/v3/pkg/infobip"
)

// checks if the MoEventVideoContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MoEventVideoContent{}

// MoEventVideoContent struct for MoEventVideoContent
type MoEventVideoContent struct {
	Type MoEventContentType
	// URL of the video.
	Url string
	// Video caption.
	Text *string
}

type _MoEventVideoContent MoEventVideoContent

// NewMoEventVideoContent instantiates a new MoEventVideoContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMoEventVideoContent(url string) *MoEventVideoContent {
	this := MoEventVideoContent{}
	this.Type = "VIDEO"
	this.Url = url
	return &this
}

// NewMoEventVideoContentWithDefaults instantiates a new MoEventVideoContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMoEventVideoContentWithDefaults() *MoEventVideoContent {
	this := MoEventVideoContent{}
	this.Type = "VIDEO"
	return &this
}

// GetUrl returns the Url field value
func (o *MoEventVideoContent) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *MoEventVideoContent) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *MoEventVideoContent) SetUrl(v string) {
	o.Url = v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *MoEventVideoContent) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoEventVideoContent) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *MoEventVideoContent) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *MoEventVideoContent) SetText(v string) {
	o.Text = &v
}

func (o MoEventVideoContent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MoEventVideoContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["url"] = o.Url
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	return toSerialize, nil
}

type NullableMoEventVideoContent struct {
	value *MoEventVideoContent
	isSet bool
}

func (v NullableMoEventVideoContent) Get() *MoEventVideoContent {
	return v.value
}

func (v *NullableMoEventVideoContent) Set(val *MoEventVideoContent) {
	v.value = val
	v.isSet = true
}

func (v NullableMoEventVideoContent) IsSet() bool {
	return v.isSet
}

func (v *NullableMoEventVideoContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMoEventVideoContent(val *MoEventVideoContent) *NullableMoEventVideoContent {
	return &NullableMoEventVideoContent{value: val, isSet: true}
}

func (v NullableMoEventVideoContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMoEventVideoContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
