/*
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

Contact: support@infobip.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package messagesapi

import (
	"encoding/json"

	. "github.com/infobip/infobip-api-go-client/v3/pkg/infobip"
)

// checks if the MoEventFormContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MoEventFormContent{}

// MoEventFormContent struct for MoEventFormContent
type MoEventFormContent struct {
	Type MoEventContentType
	// Indicates if response is private.
	IsPrivate *bool
	// List of user responses.
	Selections []MoEventFormSelection
}

type _MoEventFormContent MoEventFormContent

// NewMoEventFormContent instantiates a new MoEventFormContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMoEventFormContent(selections []MoEventFormSelection) *MoEventFormContent {
	this := MoEventFormContent{}
	this.Type = "FORM_RESPONSE"
	this.Selections = selections
	return &this
}

// NewMoEventFormContentWithDefaults instantiates a new MoEventFormContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMoEventFormContentWithDefaults() *MoEventFormContent {
	this := MoEventFormContent{}
	this.Type = "FORM_RESPONSE"
	return &this
}

// GetIsPrivate returns the IsPrivate field value if set, zero value otherwise.
func (o *MoEventFormContent) GetIsPrivate() bool {
	if o == nil || IsNil(o.IsPrivate) {
		var ret bool
		return ret
	}
	return *o.IsPrivate
}

// GetIsPrivateOk returns a tuple with the IsPrivate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoEventFormContent) GetIsPrivateOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPrivate) {
		return nil, false
	}
	return o.IsPrivate, true
}

// HasIsPrivate returns a boolean if a field has been set.
func (o *MoEventFormContent) HasIsPrivate() bool {
	if o != nil && !IsNil(o.IsPrivate) {
		return true
	}

	return false
}

// SetIsPrivate gets a reference to the given bool and assigns it to the IsPrivate field.
func (o *MoEventFormContent) SetIsPrivate(v bool) {
	o.IsPrivate = &v
}

// GetSelections returns the Selections field value
func (o *MoEventFormContent) GetSelections() []MoEventFormSelection {
	if o == nil {
		var ret []MoEventFormSelection
		return ret
	}

	return o.Selections
}

// GetSelectionsOk returns a tuple with the Selections field value
// and a boolean to check if the value has been set.
func (o *MoEventFormContent) GetSelectionsOk() ([]MoEventFormSelection, bool) {
	if o == nil {
		return nil, false
	}
	return o.Selections, true
}

// SetSelections sets field value
func (o *MoEventFormContent) SetSelections(v []MoEventFormSelection) {
	o.Selections = v
}

func (o MoEventFormContent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MoEventFormContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.IsPrivate) {
		toSerialize["isPrivate"] = o.IsPrivate
	}
	toSerialize["selections"] = o.Selections
	return toSerialize, nil
}

type NullableMoEventFormContent struct {
	value *MoEventFormContent
	isSet bool
}

func (v NullableMoEventFormContent) Get() *MoEventFormContent {
	return v.value
}

func (v *NullableMoEventFormContent) Set(val *MoEventFormContent) {
	v.value = val
	v.isSet = true
}

func (v NullableMoEventFormContent) IsSet() bool {
	return v.isSet
}

func (v *NullableMoEventFormContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMoEventFormContent(val *MoEventFormContent) *NullableMoEventFormContent {
	return &NullableMoEventFormContent{value: val, isSet: true}
}

func (v NullableMoEventFormContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMoEventFormContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
