/*
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

Contact: support@infobip.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package messagesapi

import (
	"encoding/json"

	. "github.com/infobip/infobip-api-go-client/v3/pkg/infobip"
)

// checks if the MoEventAuthenticationResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MoEventAuthenticationResponseContent{}

// MoEventAuthenticationResponseContent struct for MoEventAuthenticationResponseContent
type MoEventAuthenticationResponseContent struct {
	Type MoEventContentType
	// Authentication code.
	AuthCode *string
	// Error in case of unsuccessful authentication.
	Error *string
}

type _MoEventAuthenticationResponseContent MoEventAuthenticationResponseContent

// NewMoEventAuthenticationResponseContent instantiates a new MoEventAuthenticationResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMoEventAuthenticationResponseContent() *MoEventAuthenticationResponseContent {
	this := MoEventAuthenticationResponseContent{}
	this.Type = MOEVENTCONTENTTYPE_AUTHENTICATION_RESPONSE
	return &this
}

// NewMoEventAuthenticationResponseContentWithDefaults instantiates a new MoEventAuthenticationResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMoEventAuthenticationResponseContentWithDefaults() *MoEventAuthenticationResponseContent {
	this := MoEventAuthenticationResponseContent{}
	return &this
}

// GetAuthCode returns the AuthCode field value if set, zero value otherwise.
func (o *MoEventAuthenticationResponseContent) GetAuthCode() string {
	if o == nil || IsNil(o.AuthCode) {
		var ret string
		return ret
	}
	return *o.AuthCode
}

// GetAuthCodeOk returns a tuple with the AuthCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoEventAuthenticationResponseContent) GetAuthCodeOk() (*string, bool) {
	if o == nil || IsNil(o.AuthCode) {
		return nil, false
	}
	return o.AuthCode, true
}

// HasAuthCode returns a boolean if a field has been set.
func (o *MoEventAuthenticationResponseContent) HasAuthCode() bool {
	if o != nil && !IsNil(o.AuthCode) {
		return true
	}

	return false
}

// SetAuthCode gets a reference to the given string and assigns it to the AuthCode field.
func (o *MoEventAuthenticationResponseContent) SetAuthCode(v string) {
	o.AuthCode = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *MoEventAuthenticationResponseContent) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MoEventAuthenticationResponseContent) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *MoEventAuthenticationResponseContent) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *MoEventAuthenticationResponseContent) SetError(v string) {
	o.Error = &v
}

func (o MoEventAuthenticationResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MoEventAuthenticationResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.AuthCode) {
		toSerialize["authCode"] = o.AuthCode
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableMoEventAuthenticationResponseContent struct {
	value *MoEventAuthenticationResponseContent
	isSet bool
}

func (v NullableMoEventAuthenticationResponseContent) Get() *MoEventAuthenticationResponseContent {
	return v.value
}

func (v *NullableMoEventAuthenticationResponseContent) Set(val *MoEventAuthenticationResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableMoEventAuthenticationResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableMoEventAuthenticationResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMoEventAuthenticationResponseContent(val *MoEventAuthenticationResponseContent) *NullableMoEventAuthenticationResponseContent {
	return &NullableMoEventAuthenticationResponseContent{value: val, isSet: true}
}

func (v NullableMoEventAuthenticationResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMoEventAuthenticationResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
