/*
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

Contact: support@infobip.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package messagesapi

import (
	"encoding/json"

	. "github.com/infobip/infobip-api-go-client/v3/pkg/infobip"
)

// checks if the OttWebhooks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OttWebhooks{}

// OttWebhooks Provides options for configuring message webhooks.
type OttWebhooks struct {
	Delivery *MessageDeliveryReporting
	// Preferred delivery report content type, `application/json` or `application/xml`.
	ContentType *string
	// Additional data that can be used for identifying, managing, or monitoring a message. Data included here will also be automatically included in the message Delivery Report and Seen Report. The maximum value is 4000 characters.
	CallbackData *string
	Seen         *SeenStatusReporting
}

// NewOttWebhooks instantiates a new OttWebhooks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOttWebhooks() *OttWebhooks {
	this := OttWebhooks{}
	return &this
}

// NewOttWebhooksWithDefaults instantiates a new OttWebhooks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOttWebhooksWithDefaults() *OttWebhooks {
	this := OttWebhooks{}
	return &this
}

// GetDelivery returns the Delivery field value if set, zero value otherwise.
func (o *OttWebhooks) GetDelivery() MessageDeliveryReporting {
	if o == nil || IsNil(o.Delivery) {
		var ret MessageDeliveryReporting
		return ret
	}
	return *o.Delivery
}

// GetDeliveryOk returns a tuple with the Delivery field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OttWebhooks) GetDeliveryOk() (*MessageDeliveryReporting, bool) {
	if o == nil || IsNil(o.Delivery) {
		return nil, false
	}
	return o.Delivery, true
}

// HasDelivery returns a boolean if a field has been set.
func (o *OttWebhooks) HasDelivery() bool {
	if o != nil && !IsNil(o.Delivery) {
		return true
	}

	return false
}

// SetDelivery gets a reference to the given MessageDeliveryReporting and assigns it to the Delivery field.
func (o *OttWebhooks) SetDelivery(v MessageDeliveryReporting) {
	o.Delivery = &v
}

// GetContentType returns the ContentType field value if set, zero value otherwise.
func (o *OttWebhooks) GetContentType() string {
	if o == nil || IsNil(o.ContentType) {
		var ret string
		return ret
	}
	return *o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OttWebhooks) GetContentTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ContentType) {
		return nil, false
	}
	return o.ContentType, true
}

// HasContentType returns a boolean if a field has been set.
func (o *OttWebhooks) HasContentType() bool {
	if o != nil && !IsNil(o.ContentType) {
		return true
	}

	return false
}

// SetContentType gets a reference to the given string and assigns it to the ContentType field.
func (o *OttWebhooks) SetContentType(v string) {
	o.ContentType = &v
}

// GetCallbackData returns the CallbackData field value if set, zero value otherwise.
func (o *OttWebhooks) GetCallbackData() string {
	if o == nil || IsNil(o.CallbackData) {
		var ret string
		return ret
	}
	return *o.CallbackData
}

// GetCallbackDataOk returns a tuple with the CallbackData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OttWebhooks) GetCallbackDataOk() (*string, bool) {
	if o == nil || IsNil(o.CallbackData) {
		return nil, false
	}
	return o.CallbackData, true
}

// HasCallbackData returns a boolean if a field has been set.
func (o *OttWebhooks) HasCallbackData() bool {
	if o != nil && !IsNil(o.CallbackData) {
		return true
	}

	return false
}

// SetCallbackData gets a reference to the given string and assigns it to the CallbackData field.
func (o *OttWebhooks) SetCallbackData(v string) {
	o.CallbackData = &v
}

// GetSeen returns the Seen field value if set, zero value otherwise.
func (o *OttWebhooks) GetSeen() SeenStatusReporting {
	if o == nil || IsNil(o.Seen) {
		var ret SeenStatusReporting
		return ret
	}
	return *o.Seen
}

// GetSeenOk returns a tuple with the Seen field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OttWebhooks) GetSeenOk() (*SeenStatusReporting, bool) {
	if o == nil || IsNil(o.Seen) {
		return nil, false
	}
	return o.Seen, true
}

// HasSeen returns a boolean if a field has been set.
func (o *OttWebhooks) HasSeen() bool {
	if o != nil && !IsNil(o.Seen) {
		return true
	}

	return false
}

// SetSeen gets a reference to the given SeenStatusReporting and assigns it to the Seen field.
func (o *OttWebhooks) SetSeen(v SeenStatusReporting) {
	o.Seen = &v
}

func (o OttWebhooks) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OttWebhooks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Delivery) {
		toSerialize["delivery"] = o.Delivery
	}
	if !IsNil(o.ContentType) {
		toSerialize["contentType"] = o.ContentType
	}
	if !IsNil(o.CallbackData) {
		toSerialize["callbackData"] = o.CallbackData
	}
	if !IsNil(o.Seen) {
		toSerialize["seen"] = o.Seen
	}
	return toSerialize, nil
}

type NullableOttWebhooks struct {
	value *OttWebhooks
	isSet bool
}

func (v NullableOttWebhooks) Get() *OttWebhooks {
	return v.value
}

func (v *NullableOttWebhooks) Set(val *OttWebhooks) {
	v.value = val
	v.isSet = true
}

func (v NullableOttWebhooks) IsSet() bool {
	return v.isSet
}

func (v *NullableOttWebhooks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOttWebhooks(val *OttWebhooks) *NullableOttWebhooks {
	return &NullableOttWebhooks{value: val, isSet: true}
}

func (v NullableOttWebhooks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOttWebhooks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
