/*
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

Contact: support@infobip.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package messagesapi

import (
	"encoding/json"

	. "github.com/infobip/infobip-api-go-client/v3/pkg/infobip"
)

// checks if the UpiIntentPaymentLinkFormat type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpiIntentPaymentLinkFormat{}

// UpiIntentPaymentLinkFormat struct for UpiIntentPaymentLinkFormat
type UpiIntentPaymentLinkFormat struct {
	Type UpiIntentPaymentFormatType
	// Payment link.
	PaymentLink *string
}

type _UpiIntentPaymentLinkFormat UpiIntentPaymentLinkFormat

// NewUpiIntentPaymentLinkFormat instantiates a new UpiIntentPaymentLinkFormat object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpiIntentPaymentLinkFormat() *UpiIntentPaymentLinkFormat {
	this := UpiIntentPaymentLinkFormat{}
	this.Type = "LINK"
	return &this
}

// NewUpiIntentPaymentLinkFormatWithDefaults instantiates a new UpiIntentPaymentLinkFormat object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpiIntentPaymentLinkFormatWithDefaults() *UpiIntentPaymentLinkFormat {
	this := UpiIntentPaymentLinkFormat{}
	this.Type = "LINK"
	return &this
}

// GetPaymentLink returns the PaymentLink field value if set, zero value otherwise.
func (o *UpiIntentPaymentLinkFormat) GetPaymentLink() string {
	if o == nil || IsNil(o.PaymentLink) {
		var ret string
		return ret
	}
	return *o.PaymentLink
}

// GetPaymentLinkOk returns a tuple with the PaymentLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpiIntentPaymentLinkFormat) GetPaymentLinkOk() (*string, bool) {
	if o == nil || IsNil(o.PaymentLink) {
		return nil, false
	}
	return o.PaymentLink, true
}

// HasPaymentLink returns a boolean if a field has been set.
func (o *UpiIntentPaymentLinkFormat) HasPaymentLink() bool {
	if o != nil && !IsNil(o.PaymentLink) {
		return true
	}

	return false
}

// SetPaymentLink gets a reference to the given string and assigns it to the PaymentLink field.
func (o *UpiIntentPaymentLinkFormat) SetPaymentLink(v string) {
	o.PaymentLink = &v
}

func (o UpiIntentPaymentLinkFormat) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpiIntentPaymentLinkFormat) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.PaymentLink) {
		toSerialize["paymentLink"] = o.PaymentLink
	}
	return toSerialize, nil
}

type NullableUpiIntentPaymentLinkFormat struct {
	value *UpiIntentPaymentLinkFormat
	isSet bool
}

func (v NullableUpiIntentPaymentLinkFormat) Get() *UpiIntentPaymentLinkFormat {
	return v.value
}

func (v *NullableUpiIntentPaymentLinkFormat) Set(val *UpiIntentPaymentLinkFormat) {
	v.value = val
	v.isSet = true
}

func (v NullableUpiIntentPaymentLinkFormat) IsSet() bool {
	return v.isSet
}

func (v *NullableUpiIntentPaymentLinkFormat) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpiIntentPaymentLinkFormat(val *UpiIntentPaymentLinkFormat) *NullableUpiIntentPaymentLinkFormat {
	return &NullableUpiIntentPaymentLinkFormat{value: val, isSet: true}
}

func (v NullableUpiIntentPaymentLinkFormat) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpiIntentPaymentLinkFormat) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
