/*
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

Contact: support@infobip.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rcs

import (
	"encoding/json"

	. "github.com/infobip/infobip-api-go-client/v3/pkg/infobip"
)

// checks if the CardMedia type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CardMedia{}

// CardMedia Object defining display of card media.
type CardMedia struct {
	File      CardResourceSchema
	Thumbnail *Resource
	Height    Height
}

type _CardMedia CardMedia

// NewCardMedia instantiates a new CardMedia object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed

func NewCardMedia(file CardResourceSchema, height Height) *CardMedia {
	this := CardMedia{}
	this.File = file
	this.Height = height
	return &this
}

// NewCardMediaWithDefaults instantiates a new CardMedia object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardMediaWithDefaults() *CardMedia {
	this := CardMedia{}

	return &this
}

// GetFile returns the File field value
func (o *CardMedia) GetFile() CardResourceSchema {
	if o == nil {
		var ret CardResourceSchema
		return ret
	}

	return o.File
}

// GetFileOk returns a tuple with the File field value
// and a boolean to check if the value has been set.
func (o *CardMedia) GetFileOk() (*CardResourceSchema, bool) {
	if o == nil {
		return nil, false
	}
	return &o.File, true
}

// SetFile sets field value
func (o *CardMedia) SetFile(v CardResourceSchema) {
	o.File = v
}

// GetThumbnail returns the Thumbnail field value if set, zero value otherwise.
func (o *CardMedia) GetThumbnail() Resource {
	if o == nil || IsNil(o.Thumbnail) {
		var ret Resource
		return ret
	}
	return *o.Thumbnail
}

// GetThumbnailOk returns a tuple with the Thumbnail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardMedia) GetThumbnailOk() (*Resource, bool) {
	if o == nil || IsNil(o.Thumbnail) {
		return nil, false
	}
	return o.Thumbnail, true
}

// HasThumbnail returns a boolean if a field has been set.
func (o *CardMedia) HasThumbnail() bool {
	if o != nil && !IsNil(o.Thumbnail) {
		return true
	}

	return false
}

// SetThumbnail gets a reference to the given Resource and assigns it to the Thumbnail field.
func (o *CardMedia) SetThumbnail(v Resource) {
	o.Thumbnail = &v
}

// GetHeight returns the Height field value
func (o *CardMedia) GetHeight() Height {
	if o == nil {
		var ret Height
		return ret
	}

	return o.Height
}

// GetHeightOk returns a tuple with the Height field value
// and a boolean to check if the value has been set.
func (o *CardMedia) GetHeightOk() (*Height, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Height, true
}

// SetHeight sets field value
func (o *CardMedia) SetHeight(v Height) {
	o.Height = v
}

func (o CardMedia) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CardMedia) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["file"] = o.File
	if !IsNil(o.Thumbnail) {
		toSerialize["thumbnail"] = o.Thumbnail
	}
	toSerialize["height"] = o.Height
	return toSerialize, nil
}

type NullableCardMedia struct {
	value *CardMedia
	isSet bool
}

func (v NullableCardMedia) Get() *CardMedia {
	return v.value
}

func (v *NullableCardMedia) Set(val *CardMedia) {
	v.value = val
	v.isSet = true
}

func (v NullableCardMedia) IsSet() bool {
	return v.isSet
}

func (v *NullableCardMedia) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardMedia(val *CardMedia) *NullableCardMedia {
	return &NullableCardMedia{value: val, isSet: true}
}

func (v NullableCardMedia) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardMedia) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
