/*
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

Contact: support@infobip.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rcs

import (
	"encoding/json"

	. "github.com/infobip/infobip-api-go-client/v3/pkg/infobip"
)

// checks if the DialPhoneSuggestion type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DialPhoneSuggestion{}

// DialPhoneSuggestion Opens the user's default dialer app with the agent-specified phone number filled in.
type DialPhoneSuggestion struct {
	Type SuggestionType
	// Suggestion text.
	Text string
	// Value which is going to be sent as a reply to a suggestion.
	PostbackData string
	// Valid phone number.
	PhoneNumber string
}

type _DialPhoneSuggestion DialPhoneSuggestion

// NewDialPhoneSuggestion instantiates a new DialPhoneSuggestion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDialPhoneSuggestion(text string, postbackData string, phoneNumber string) *DialPhoneSuggestion {
	this := DialPhoneSuggestion{}
	this.Type = "DIAL_PHONE"
	this.Text = text
	this.PostbackData = postbackData
	this.PhoneNumber = phoneNumber
	return &this
}

// NewDialPhoneSuggestionWithDefaults instantiates a new DialPhoneSuggestion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDialPhoneSuggestionWithDefaults() *DialPhoneSuggestion {
	this := DialPhoneSuggestion{}
	this.Type = "DIAL_PHONE"
	return &this
}

// GetText returns the Text field value
func (o *DialPhoneSuggestion) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *DialPhoneSuggestion) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *DialPhoneSuggestion) SetText(v string) {
	o.Text = v
}

// GetPostbackData returns the PostbackData field value
func (o *DialPhoneSuggestion) GetPostbackData() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PostbackData
}

// GetPostbackDataOk returns a tuple with the PostbackData field value
// and a boolean to check if the value has been set.
func (o *DialPhoneSuggestion) GetPostbackDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PostbackData, true
}

// SetPostbackData sets field value
func (o *DialPhoneSuggestion) SetPostbackData(v string) {
	o.PostbackData = v
}

// GetPhoneNumber returns the PhoneNumber field value
func (o *DialPhoneSuggestion) GetPhoneNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value
// and a boolean to check if the value has been set.
func (o *DialPhoneSuggestion) GetPhoneNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PhoneNumber, true
}

// SetPhoneNumber sets field value
func (o *DialPhoneSuggestion) SetPhoneNumber(v string) {
	o.PhoneNumber = v
}

func (o DialPhoneSuggestion) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DialPhoneSuggestion) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["text"] = o.Text
	toSerialize["postbackData"] = o.PostbackData
	toSerialize["phoneNumber"] = o.PhoneNumber
	return toSerialize, nil
}

type NullableDialPhoneSuggestion struct {
	value *DialPhoneSuggestion
	isSet bool
}

func (v NullableDialPhoneSuggestion) Get() *DialPhoneSuggestion {
	return v.value
}

func (v *NullableDialPhoneSuggestion) Set(val *DialPhoneSuggestion) {
	v.value = val
	v.isSet = true
}

func (v NullableDialPhoneSuggestion) IsSet() bool {
	return v.isSet
}

func (v *NullableDialPhoneSuggestion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDialPhoneSuggestion(val *DialPhoneSuggestion) *NullableDialPhoneSuggestion {
	return &NullableDialPhoneSuggestion{value: val, isSet: true}
}

func (v NullableDialPhoneSuggestion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDialPhoneSuggestion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
