/*
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

Contact: support@infobip.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rcs

import (
	"encoding/json"

	. "github.com/infobip/infobip-api-go-client/v3/pkg/infobip"
)

// checks if the IsTypingEvents type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IsTypingEvents{}

// IsTypingEvents struct for IsTypingEvents
type IsTypingEvents struct {
	// Collection of typing indicator events.
	Results []IsTypingEvent
	// The number of events returned in the results array.
	EventCount int32
	// The number of events that have not been pulled in.
	PendingEventCount int32
}

type _IsTypingEvents IsTypingEvents

// NewIsTypingEvents instantiates a new IsTypingEvents object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed

func NewIsTypingEvents(results []IsTypingEvent, eventCount int32, pendingEventCount int32) *IsTypingEvents {
	this := IsTypingEvents{}
	this.Results = results
	this.EventCount = eventCount
	this.PendingEventCount = pendingEventCount
	return &this
}

// NewIsTypingEventsWithDefaults instantiates a new IsTypingEvents object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIsTypingEventsWithDefaults() *IsTypingEvents {
	this := IsTypingEvents{}

	return &this
}

// GetResults returns the Results field value
func (o *IsTypingEvents) GetResults() []IsTypingEvent {
	if o == nil {
		var ret []IsTypingEvent
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *IsTypingEvents) GetResultsOk() ([]IsTypingEvent, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *IsTypingEvents) SetResults(v []IsTypingEvent) {
	o.Results = v
}

// GetEventCount returns the EventCount field value
func (o *IsTypingEvents) GetEventCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.EventCount
}

// GetEventCountOk returns a tuple with the EventCount field value
// and a boolean to check if the value has been set.
func (o *IsTypingEvents) GetEventCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventCount, true
}

// SetEventCount sets field value
func (o *IsTypingEvents) SetEventCount(v int32) {
	o.EventCount = v
}

// GetPendingEventCount returns the PendingEventCount field value
func (o *IsTypingEvents) GetPendingEventCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PendingEventCount
}

// GetPendingEventCountOk returns a tuple with the PendingEventCount field value
// and a boolean to check if the value has been set.
func (o *IsTypingEvents) GetPendingEventCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PendingEventCount, true
}

// SetPendingEventCount sets field value
func (o *IsTypingEvents) SetPendingEventCount(v int32) {
	o.PendingEventCount = v
}

func (o IsTypingEvents) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IsTypingEvents) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["results"] = o.Results
	toSerialize["eventCount"] = o.EventCount
	toSerialize["pendingEventCount"] = o.PendingEventCount
	return toSerialize, nil
}

type NullableIsTypingEvents struct {
	value *IsTypingEvents
	isSet bool
}

func (v NullableIsTypingEvents) Get() *IsTypingEvents {
	return v.value
}

func (v *NullableIsTypingEvents) Set(val *IsTypingEvents) {
	v.value = val
	v.isSet = true
}

func (v NullableIsTypingEvents) IsSet() bool {
	return v.isSet
}

func (v *NullableIsTypingEvents) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIsTypingEvents(val *IsTypingEvents) *NullableIsTypingEvents {
	return &NullableIsTypingEvents{value: val, isSet: true}
}

func (v NullableIsTypingEvents) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIsTypingEvents) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
