/*
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

Contact: support@infobip.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rcs

import (
	"encoding/json"

	. "github.com/infobip/infobip-api-go-client/v3/pkg/infobip"
)

// checks if the OutboundEventTypingIndicatorContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutboundEventTypingIndicatorContent{}

// OutboundEventTypingIndicatorContent struct for OutboundEventTypingIndicatorContent
type OutboundEventTypingIndicatorContent struct {
	Type OutboundEventContentType
}

type _OutboundEventTypingIndicatorContent OutboundEventTypingIndicatorContent

// NewOutboundEventTypingIndicatorContent instantiates a new OutboundEventTypingIndicatorContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutboundEventTypingIndicatorContent() *OutboundEventTypingIndicatorContent {
	this := OutboundEventTypingIndicatorContent{}
	this.Type = "TYPING_INDICATOR"
	return &this
}

// NewOutboundEventTypingIndicatorContentWithDefaults instantiates a new OutboundEventTypingIndicatorContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutboundEventTypingIndicatorContentWithDefaults() *OutboundEventTypingIndicatorContent {
	this := OutboundEventTypingIndicatorContent{}
	this.Type = "TYPING_INDICATOR"
	return &this
}

func (o OutboundEventTypingIndicatorContent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutboundEventTypingIndicatorContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

type NullableOutboundEventTypingIndicatorContent struct {
	value *OutboundEventTypingIndicatorContent
	isSet bool
}

func (v NullableOutboundEventTypingIndicatorContent) Get() *OutboundEventTypingIndicatorContent {
	return v.value
}

func (v *NullableOutboundEventTypingIndicatorContent) Set(val *OutboundEventTypingIndicatorContent) {
	v.value = val
	v.isSet = true
}

func (v NullableOutboundEventTypingIndicatorContent) IsSet() bool {
	return v.isSet
}

func (v *NullableOutboundEventTypingIndicatorContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutboundEventTypingIndicatorContent(val *OutboundEventTypingIndicatorContent) *NullableOutboundEventTypingIndicatorContent {
	return &NullableOutboundEventTypingIndicatorContent{value: val, isSet: true}
}

func (v NullableOutboundEventTypingIndicatorContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutboundEventTypingIndicatorContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
