/*
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

Contact: support@infobip.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rcs

import (
	"encoding/json"

	. "github.com/infobip/infobip-api-go-client/v3/pkg/infobip"
)

// checks if the OutboundTextContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutboundTextContent{}

// OutboundTextContent struct for OutboundTextContent
type OutboundTextContent struct {
	Type OutboundMessageContentType
	// Message text.
	Text string
	// List of suggestions.
	Suggestions []Suggestion
}

type _OutboundTextContent OutboundTextContent

// NewOutboundTextContent instantiates a new OutboundTextContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutboundTextContent(text string) *OutboundTextContent {
	this := OutboundTextContent{}
	this.Type = "TEXT"
	this.Text = text
	return &this
}

// NewOutboundTextContentWithDefaults instantiates a new OutboundTextContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutboundTextContentWithDefaults() *OutboundTextContent {
	this := OutboundTextContent{}
	this.Type = "TEXT"
	return &this
}

// GetText returns the Text field value
func (o *OutboundTextContent) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *OutboundTextContent) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *OutboundTextContent) SetText(v string) {
	o.Text = v
}

// GetSuggestions returns the Suggestions field value if set, zero value otherwise.
func (o *OutboundTextContent) GetSuggestions() []Suggestion {
	if o == nil || IsNil(o.Suggestions) {
		var ret []Suggestion
		return ret
	}
	return o.Suggestions
}

// GetSuggestionsOk returns a tuple with the Suggestions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutboundTextContent) GetSuggestionsOk() ([]Suggestion, bool) {
	if o == nil || IsNil(o.Suggestions) {
		return nil, false
	}
	return o.Suggestions, true
}

// HasSuggestions returns a boolean if a field has been set.
func (o *OutboundTextContent) HasSuggestions() bool {
	if o != nil && !IsNil(o.Suggestions) {
		return true
	}

	return false
}

// SetSuggestions gets a reference to the given []Suggestion and assigns it to the Suggestions field.
func (o *OutboundTextContent) SetSuggestions(v []Suggestion) {
	o.Suggestions = v
}

func (o OutboundTextContent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutboundTextContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["text"] = o.Text
	if !IsNil(o.Suggestions) {
		toSerialize["suggestions"] = o.Suggestions
	}
	return toSerialize, nil
}

type NullableOutboundTextContent struct {
	value *OutboundTextContent
	isSet bool
}

func (v NullableOutboundTextContent) Get() *OutboundTextContent {
	return v.value
}

func (v *NullableOutboundTextContent) Set(val *OutboundTextContent) {
	v.value = val
	v.isSet = true
}

func (v NullableOutboundTextContent) IsSet() bool {
	return v.isSet
}

func (v *NullableOutboundTextContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutboundTextContent(val *OutboundTextContent) *NullableOutboundTextContent {
	return &NullableOutboundTextContent{value: val, isSet: true}
}

func (v NullableOutboundTextContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutboundTextContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
