/*
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

Contact: support@infobip.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rcs

import (
	"encoding/json"
	"fmt"
)

// WebviewViewModeType Type of the webview's view mode. It must be defined when `application` is set to `WEBVIEW`. Following options are available: * `FULL`: The web page takes up the full screen on a mobile phone. * `HALF`: The web page takes up half of the screen on a mobile phone. * `TALL`: The web page takes up three quarters of the screen on a mobile phone.
type WebviewViewModeType string

// List of WebviewViewModeType
const (
	WEBVIEWVIEWMODETYPE_FULL WebviewViewModeType = "FULL"
	WEBVIEWVIEWMODETYPE_HALF WebviewViewModeType = "HALF"
	WEBVIEWVIEWMODETYPE_TALL WebviewViewModeType = "TALL"
)

// All allowed values of WebviewViewModeType enum
var AllowedWebviewViewModeTypeEnumValues = []WebviewViewModeType{
	"FULL",
	"HALF",
	"TALL",
}

func (v *WebviewViewModeType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := WebviewViewModeType(value)
	for _, existing := range AllowedWebviewViewModeTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid WebviewViewModeType", value)
}

// NewWebviewViewModeTypeFromValue returns a pointer to a valid WebviewViewModeType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewWebviewViewModeTypeFromValue(v string) (*WebviewViewModeType, error) {
	ev := WebviewViewModeType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for WebviewViewModeType: valid values are %v", v, AllowedWebviewViewModeTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v WebviewViewModeType) IsValid() bool {
	for _, existing := range AllowedWebviewViewModeTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to WebviewViewModeType value
func (v WebviewViewModeType) Ptr() *WebviewViewModeType {
	return &v
}

type NullableWebviewViewModeType struct {
	value *WebviewViewModeType
	isSet bool
}

func (v NullableWebviewViewModeType) Get() *WebviewViewModeType {
	return v.value
}

func (v *NullableWebviewViewModeType) Set(val *WebviewViewModeType) {
	v.value = val
	v.isSet = true
}

func (v NullableWebviewViewModeType) IsSet() bool {
	return v.isSet
}

func (v *NullableWebviewViewModeType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebviewViewModeType(val *WebviewViewModeType) *NullableWebviewViewModeType {
	return &NullableWebviewViewModeType{value: val, isSet: true}
}

func (v NullableWebviewViewModeType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebviewViewModeType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
