/*
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

Contact: support@infobip.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package email

import (
	"encoding/json"

	. "github.com/infobip/infobip-api-go-client/v3/pkg/infobip"
)

// checks if the BulkUpdateStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkUpdateStatusResponse{}

// BulkUpdateStatusResponse struct for BulkUpdateStatusResponse
type BulkUpdateStatusResponse struct {
	BulkId *string
	Status *BulkStatus
}

// NewBulkUpdateStatusResponse instantiates a new BulkUpdateStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed

func NewBulkUpdateStatusResponse() *BulkUpdateStatusResponse {
	this := BulkUpdateStatusResponse{}
	return &this
}

// NewBulkUpdateStatusResponseWithDefaults instantiates a new BulkUpdateStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkUpdateStatusResponseWithDefaults() *BulkUpdateStatusResponse {
	this := BulkUpdateStatusResponse{}

	return &this
}

// GetBulkId returns the BulkId field value if set, zero value otherwise.
func (o *BulkUpdateStatusResponse) GetBulkId() string {
	if o == nil || IsNil(o.BulkId) {
		var ret string
		return ret
	}
	return *o.BulkId
}

// GetBulkIdOk returns a tuple with the BulkId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkUpdateStatusResponse) GetBulkIdOk() (*string, bool) {
	if o == nil || IsNil(o.BulkId) {
		return nil, false
	}
	return o.BulkId, true
}

// HasBulkId returns a boolean if a field has been set.
func (o *BulkUpdateStatusResponse) HasBulkId() bool {
	if o != nil && !IsNil(o.BulkId) {
		return true
	}

	return false
}

// SetBulkId gets a reference to the given string and assigns it to the BulkId field.
func (o *BulkUpdateStatusResponse) SetBulkId(v string) {
	o.BulkId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *BulkUpdateStatusResponse) GetStatus() BulkStatus {
	if o == nil || IsNil(o.Status) {
		var ret BulkStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkUpdateStatusResponse) GetStatusOk() (*BulkStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *BulkUpdateStatusResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given BulkStatus and assigns it to the Status field.
func (o *BulkUpdateStatusResponse) SetStatus(v BulkStatus) {
	o.Status = &v
}

func (o BulkUpdateStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkUpdateStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BulkId) {
		toSerialize["bulkId"] = o.BulkId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableBulkUpdateStatusResponse struct {
	value *BulkUpdateStatusResponse
	isSet bool
}

func (v NullableBulkUpdateStatusResponse) Get() *BulkUpdateStatusResponse {
	return v.value
}

func (v *NullableBulkUpdateStatusResponse) Set(val *BulkUpdateStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkUpdateStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkUpdateStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkUpdateStatusResponse(val *BulkUpdateStatusResponse) *NullableBulkUpdateStatusResponse {
	return &NullableBulkUpdateStatusResponse{value: val, isSet: true}
}

func (v NullableBulkUpdateStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkUpdateStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
