/*
Infobip Client API Libraries OpenAPI Specification

OpenAPI specification containing public endpoints supported in client API libraries.

Contact: support@infobip.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package email

import (
	"encoding/json"

	. "github.com/infobip/infobip-api-go-client/v3/pkg/infobip"
)

// checks if the ValidationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValidationResponse{}

// ValidationResponse Validation response
type ValidationResponse struct {
	// The validated email address.
	To string
	// Indicates whether email address is valid.
	ValidMailbox string
	// Indicates whether email address syntax is valid.
	ValidSyntax bool
	// Indicates catch all status of email address.
	CatchAll bool
	// Suggests similar alternate address that may be valid.
	DidYouMean *string
	// Indicates whether email address is disposable. A disposable email address is a temporary address that is often used for short-term purposes and can be discarded after use.
	Disposable bool
	// Indicates whether email address is role-based. A role-based email address is one that is associated with a specific function or group within an organization, such as marketing@example.org, rather than an individual person.
	RoleBased bool
	Reason    *ValidationReason
	Risk      ApiRisk
	// This field is provided when the validMailbox status is 'unknown' or 'false', offering specific explanations for why the email address has been assigned that status.
	DetailedReasons *string
}

type _ValidationResponse ValidationResponse

// NewValidationResponse instantiates a new ValidationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed

func NewValidationResponse(to string, validMailbox string, validSyntax bool, catchAll bool, disposable bool, roleBased bool, risk ApiRisk) *ValidationResponse {
	this := ValidationResponse{}
	this.To = to
	this.ValidMailbox = validMailbox
	this.ValidSyntax = validSyntax
	this.CatchAll = catchAll
	this.Disposable = disposable
	this.RoleBased = roleBased
	this.Risk = risk
	return &this
}

// NewValidationResponseWithDefaults instantiates a new ValidationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValidationResponseWithDefaults() *ValidationResponse {
	this := ValidationResponse{}

	return &this
}

// GetTo returns the To field value
func (o *ValidationResponse) GetTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *ValidationResponse) GetToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *ValidationResponse) SetTo(v string) {
	o.To = v
}

// GetValidMailbox returns the ValidMailbox field value
func (o *ValidationResponse) GetValidMailbox() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ValidMailbox
}

// GetValidMailboxOk returns a tuple with the ValidMailbox field value
// and a boolean to check if the value has been set.
func (o *ValidationResponse) GetValidMailboxOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValidMailbox, true
}

// SetValidMailbox sets field value
func (o *ValidationResponse) SetValidMailbox(v string) {
	o.ValidMailbox = v
}

// GetValidSyntax returns the ValidSyntax field value
func (o *ValidationResponse) GetValidSyntax() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ValidSyntax
}

// GetValidSyntaxOk returns a tuple with the ValidSyntax field value
// and a boolean to check if the value has been set.
func (o *ValidationResponse) GetValidSyntaxOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValidSyntax, true
}

// SetValidSyntax sets field value
func (o *ValidationResponse) SetValidSyntax(v bool) {
	o.ValidSyntax = v
}

// GetCatchAll returns the CatchAll field value
func (o *ValidationResponse) GetCatchAll() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CatchAll
}

// GetCatchAllOk returns a tuple with the CatchAll field value
// and a boolean to check if the value has been set.
func (o *ValidationResponse) GetCatchAllOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CatchAll, true
}

// SetCatchAll sets field value
func (o *ValidationResponse) SetCatchAll(v bool) {
	o.CatchAll = v
}

// GetDidYouMean returns the DidYouMean field value if set, zero value otherwise.
func (o *ValidationResponse) GetDidYouMean() string {
	if o == nil || IsNil(o.DidYouMean) {
		var ret string
		return ret
	}
	return *o.DidYouMean
}

// GetDidYouMeanOk returns a tuple with the DidYouMean field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidationResponse) GetDidYouMeanOk() (*string, bool) {
	if o == nil || IsNil(o.DidYouMean) {
		return nil, false
	}
	return o.DidYouMean, true
}

// HasDidYouMean returns a boolean if a field has been set.
func (o *ValidationResponse) HasDidYouMean() bool {
	if o != nil && !IsNil(o.DidYouMean) {
		return true
	}

	return false
}

// SetDidYouMean gets a reference to the given string and assigns it to the DidYouMean field.
func (o *ValidationResponse) SetDidYouMean(v string) {
	o.DidYouMean = &v
}

// GetDisposable returns the Disposable field value
func (o *ValidationResponse) GetDisposable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Disposable
}

// GetDisposableOk returns a tuple with the Disposable field value
// and a boolean to check if the value has been set.
func (o *ValidationResponse) GetDisposableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Disposable, true
}

// SetDisposable sets field value
func (o *ValidationResponse) SetDisposable(v bool) {
	o.Disposable = v
}

// GetRoleBased returns the RoleBased field value
func (o *ValidationResponse) GetRoleBased() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.RoleBased
}

// GetRoleBasedOk returns a tuple with the RoleBased field value
// and a boolean to check if the value has been set.
func (o *ValidationResponse) GetRoleBasedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoleBased, true
}

// SetRoleBased sets field value
func (o *ValidationResponse) SetRoleBased(v bool) {
	o.RoleBased = v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *ValidationResponse) GetReason() ValidationReason {
	if o == nil || IsNil(o.Reason) {
		var ret ValidationReason
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidationResponse) GetReasonOk() (*ValidationReason, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *ValidationResponse) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given ValidationReason and assigns it to the Reason field.
func (o *ValidationResponse) SetReason(v ValidationReason) {
	o.Reason = &v
}

// GetRisk returns the Risk field value
func (o *ValidationResponse) GetRisk() ApiRisk {
	if o == nil {
		var ret ApiRisk
		return ret
	}

	return o.Risk
}

// GetRiskOk returns a tuple with the Risk field value
// and a boolean to check if the value has been set.
func (o *ValidationResponse) GetRiskOk() (*ApiRisk, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Risk, true
}

// SetRisk sets field value
func (o *ValidationResponse) SetRisk(v ApiRisk) {
	o.Risk = v
}

// GetDetailedReasons returns the DetailedReasons field value if set, zero value otherwise.
func (o *ValidationResponse) GetDetailedReasons() string {
	if o == nil || IsNil(o.DetailedReasons) {
		var ret string
		return ret
	}
	return *o.DetailedReasons
}

// GetDetailedReasonsOk returns a tuple with the DetailedReasons field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidationResponse) GetDetailedReasonsOk() (*string, bool) {
	if o == nil || IsNil(o.DetailedReasons) {
		return nil, false
	}
	return o.DetailedReasons, true
}

// HasDetailedReasons returns a boolean if a field has been set.
func (o *ValidationResponse) HasDetailedReasons() bool {
	if o != nil && !IsNil(o.DetailedReasons) {
		return true
	}

	return false
}

// SetDetailedReasons gets a reference to the given string and assigns it to the DetailedReasons field.
func (o *ValidationResponse) SetDetailedReasons(v string) {
	o.DetailedReasons = &v
}

func (o ValidationResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValidationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["to"] = o.To
	toSerialize["validMailbox"] = o.ValidMailbox
	toSerialize["validSyntax"] = o.ValidSyntax
	toSerialize["catchAll"] = o.CatchAll
	if !IsNil(o.DidYouMean) {
		toSerialize["didYouMean"] = o.DidYouMean
	}
	toSerialize["disposable"] = o.Disposable
	toSerialize["roleBased"] = o.RoleBased
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	toSerialize["risk"] = o.Risk
	if !IsNil(o.DetailedReasons) {
		toSerialize["detailedReasons"] = o.DetailedReasons
	}
	return toSerialize, nil
}

type NullableValidationResponse struct {
	value *ValidationResponse
	isSet bool
}

func (v NullableValidationResponse) Get() *ValidationResponse {
	return v.value
}

func (v *NullableValidationResponse) Set(val *ValidationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableValidationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableValidationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidationResponse(val *ValidationResponse) *NullableValidationResponse {
	return &NullableValidationResponse{value: val, isSet: true}
}

func (v NullableValidationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
